### ISSUE TITLE
Upgrade Server

### ISSUE THREAD

**Issue by erikjlane** [itzg/docker-minecraft-bedrock-server#108]
My kids can no longer connect to my server, as the clients have upgraded, but the server is lagging behind. I've examined the files in the docker container, but I haven't yet been able to figure out how to force an upgrade, since the docker hub image still seems to have the old server version.

Is there a way that I can extract the contents of the 1.16.100 server file into the docker container and change some settings so that it will pick up the new server?

Thanks!

**Comment by paulogleuwyo** [comment]
You should kill and remove the existing docker container. Then either in your Dockerfile or in the command line add -e VERSION=LATEST

I also had this issue running Minecraft client on Windows 10 and Android and now both of them are able to connect to the 1.16.100 server instance file.

**Comment by paulogleuwyo** [comment]
> My kids can no longer connect to my server, as the clients have upgraded, but the server is lagging behind. I've examined the files in the docker container, but I haven't yet been able to figure out how to force an upgrade, since the docker hub image still seems to have the old server version.
> 
> Is there a way that I can extract the contents of the 1.16.100 server file into the docker container and change some settings so that it will pick up the new server?
> 
> Thanks!



You should kill and remove the existing docker container. Then either in your Dockerfile or in the command line add -e VERSION=LATEST

I also had this issue running Minecraft client on Windows 10 and Android and now both of them are able to connect to the 1.16.100 server instance file.

**Comment by erikjlane** [comment]
Thank you for the reply. However, my docker file already shows VERSION=LATEST and the server was stuck on 1.16.60 (I think). Everything looks like it should, I think.

However, just in case, I stopped the container and restarted it. I use Portainer, and don't know the command line for Docker very well yet, even though I prefer CLI for most things. It fought me about removing the image, even with containers stopped. When I restarted the containers, they got the new version and everything worked! They didn't report trying to get the new image, but I guess they did in the background.

Thank you!

**Comment by itzg** [comment]
It will only attempt to grab the latest version at container startup/restart, so that makes sense that fixed it. Odd you didn't see a log mentioning that though.

**Comment by erikjlane** [comment]
Easily possible that I missed it in the log file. I didn't spend much time looking at them. I also don't use them much, so I could have looked right over the relevant part without noticing.

I thought that I had to update the image by hand, and didn't know about this 'only grab the latest version at container startup' so it was operator error. If only I had known that it was so simple! :) Thanks for the education!

**Comment by radu-neacsu** [comment]
use VERSION: "1.16.100.04" in docker compose or -e VERSION: "1.16.100.04" for docker run

**Comment by erikjlane** [comment]
Well, it's working now for me. I *really* don't want to hardcode a version number in there, because the next time that the server needs updating I want it to be able to pick it up without changes from me. So having version=latest is what I want.

Thanks for the response, though.

**Comment by itzg** [comment]
VERSION=LATEST sounds like it worked fine, it was just a clarification issue on when the server does upgrade. I'm going to close the issue to avoid confusion.
