### ISSUE TITLE
Mapping whitelist.json in docker-compose

### ISSUE THREAD

**Issue by accessTechnology** [itzg/docker-minecraft-bedrock-server#109]
The docs state:

"set the WHITE_LIST environment variable to true and **map in a whitelist.json** that is custom-crafted to the container", but offer no instructions on how to do this.

Please can someone demonstrate how to achieve this.

**Comment by itzg** [comment]
Added a link to gamepedia (a24e86470aae3aa37f5f9fcb442a7cba142923c8)
