### ISSUE TITLE
Feature Request - arm/arm64 support (raspberrypi)

### ISSUE THREAD

**Issue by ionTrix** [itzg/docker-minecraft-bedrock-server#112]
Would love to try running this on my Raspberry Pi 3 that's currently running a 64bit beta version of raspios (2020-08-20-raspios-buster-arm64-lite) with docker. I have Portainer and a few others ive got working and could switch to the stable 32bit for testing as well. Thanks!

**Comment by itzg** [comment]
Mojang does not provide a build of bedrock edition for ARM / RaspberryPi unfortunately:

https://bugs.mojang.com/browse/BDS-53?focusedCommentId=489391&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-489391
