### ISSUE TITLE
Stuck downloading update

### ISSUE THREAD

**Issue by PatrickBig** [itzg/docker-minecraft-bedrock-server#113]
I have had this running on my AKS instance without any hiccups until today. I have not played in a couple of days and noticed this in the logs:

time="2020-11-30T23:21:32Z" level=debug msg="Using /data to match uid and gid"
time="2020-11-30T23:21:32Z" level=debug msg="Resolved UID=0 from match path"
time="2020-11-30T23:21:32Z" level=debug msg="Resolved GID=0 from match path"
time="2020-11-30T23:21:32Z" level=debug msg="stdin is detached, so forwarding is disabled"
Downloading Bedrock server version 1.16.101.01 ...

I have let it sit there trying to download for over an hour and it's not really getting anywhere. Anyone have any ideas?

**Comment by itzg** [comment]
I have noticed that download can be slow sometimes...but not an hour long kind of slow. And downloading from AKS should be the most optimal since the files are probably hosted on S3. 

Have you tried forcing a restart of the pod? That download might just be stuck.

**Comment by PatrickBig** [comment]
Yeah, I have even re-deployed completely.

**Comment by itzg** [comment]
...actually, they probably host on Azure CDN now.

**Comment by itzg** [comment]
If you let it pull the latest image, I have added a `DEBUG` environment variable that can be set to "true"

**Comment by PatrickBig** [comment]
That helped me figure it out!

I was out of disk space.... embarrassing
