### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by asafs133** [itzg/docker-minecraft-bedrock-server#114]
Hi,
When I execute the following command:
docker run -d -it -e EULA=TRUE -p 19132:19132/udp itzg/minecraft-bedrock-server

I received the following exception:
standard_init_linux.go:211: exec user process caused "exec format error"

Do you know why it happens?

**Comment by itzg** [comment]
Are you trying to run the container on an ARM platform like RaspberryPi?

**Comment by asafs133** [comment]
Yes, is it not supporting the ARM platform? if so, what alternative I have?

**Comment by itzg** [comment]
Looks like you can vote at https://feedback.minecraft.net/hc/en-us/community/posts/360022601432-Dedicated-Servers-for-ARM-Devices or run on a 64-bit x86 platform instead.
