### ISSUE TITLE
Error downloading the server binary: curl transfer closed with N bytes remaining to read

### ISSUE THREAD

**Issue by chr15m** [itzg/docker-minecraft-bedrock-server#115]
I'm seeing this in the docker logs:

```
Downloading Bedrock server version 1.16.101.01 ...
curl: (18) transfer closed with 69195496 bytes remaining to read
ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-1.16.101.01.zip
      Double check that the given VERSION is valid
```

I tried with a couple of other versions but I got the same result. Any tips on how I can diagnose this?

**Comment by itzg** [comment]
Add a `DEBUG=true` environment variable and that will turn on verbose mode of curl. Let's see if that reveals any more clues.

**Comment by chr15m** [comment]
I ran it with the `DEBUG=true` environment variable set, but [un]fortunately this time the download did not fail and the server container was deployed correctly. What might be helpful for the future is an environment variable (or instructions) to load the zip directly from `/data` instead of downloading it, for people on flaky connections.

**Comment by itzg** [comment]
Great idea about being able to pre-download the zip. I created #121 to track that.
