### ISSUE TITLE
Space in name in WHITE_LIST_USERS not parsed correctly

### ISSUE THREAD

**Issue by fnord123** [itzg/docker-minecraft-bedrock-server#116]
I have been trying to use WHITE_LIST_USERS and any name that has a space in it gets truncated.  So e.g. if WHITE_LIST_USERS="Foo,Bar Bas", the generated whitelist has entries for Foo and Bar, rather than Foo and Bar Bas.

**Comment by itzg** [comment]
Thanks for reporting this. My Xbox username also has a space in it, so this eventually would have been an issue for me too :)

**Comment by itzg** [comment]
Latest image on Docker Hub now includes this fix.

**Comment by fnord123** [comment]
I just force pulled the latest and verified that this fixed it. Thank you!
