### ISSUE TITLE
Kubernetes unable to pull image 

### ISSUE THREAD

**Issue by RoyalDecline** [itzg/docker-minecraft-bedrock-server#118]
Using Kubernetes with a pretty close to standard layout. PV claim looks good and other pods have no network/DNS issues. 
Also,  Thanks for even maintaining a Kube release.   Really appreciated. 

[RoyalDecline@MegaNode ~]$ kubectl logs  -n minecraft minecraft-84c986cdbd-9zl5p
time="2020-12-10T03:30:03Z" level=debug msg="Using /data to match uid and gid"
time="2020-12-10T03:30:03Z" level=debug msg="Resolved UID=1000 from match path"
time="2020-12-10T03:30:03Z" level=debug msg="Resolved GID=1000 from match path"
time="2020-12-10T03:30:03Z" level=debug msg="stdin is detached, so forwarding is disabled"
Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
2020/12/10 03:30:03 Failed to get from URLGet https://www.minecraft.net/en-us/download/server/bedrock/: x509: certificate is valid for ingress.local, not www.minecraft.net

**Comment by itzg** [comment]
It sounds a virus scanning proxy, corporate proxy, etc is intercepting and swapping out the cert. Try adding the `DEBUG` env var set to "TRUE" and see if the verbose curl logs tell you more.

**Comment by itzg** [comment]
...just noticed it looks like your ingress must be somehow intercepting outgoing (instead of normally inbound) HTTP requests since the cert's subject apparently is `ingress.local`. Misconfigured Istio/Linkerd perhaps?

**Comment by itzg** [comment]
I'm going to close this issue since it doesn't seem to be related at all to the repo itself, but I'll be glad to brainstorm here still.

**Comment by RoyalDecline** [comment]
No virus scan or corporate firewalls here.  This is in the homelab sitting behind a generic firewall router combo.  I

 Here is with Debug.
[dcorley@whore minecraft]$ kubectl get pods -n minecraft 
NAME                         READY   STATUS             RESTARTS   AGE
minecraft-84c986cdbd-9zl5p   0/1     CrashLoopBackOff   212        17h
minecraft-f8968cc58-r68c7    0/1     CrashLoopBackOff   1          11s
[dcorley@whore minecraft]$ kubectl logs -n minecraft minecraft-f8968cc58-r68c7
time="2020-12-10T20:42:23Z" level=debug msg="Using /data to match uid and gid"
time="2020-12-10T20:42:23Z" level=debug msg="Resolved UID=1000 from match path"
time="2020-12-10T20:42:23Z" level=debug msg="Resolved GID=1000 from match path"
time="2020-12-10T20:42:23Z" level=debug msg="stdin is detached, so forwarding is disabled"
+ curlArgs=(-v)
+ downloadPage=https://www.minecraft.net/en-us/download/server/bedrock/
+ [[ TRUE != TRUE ]]
+ case ${VERSION^^} in
+ for a in data-bi-prtid data-platform
++ restify --attribute=data-bi-prtid=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock/
++ jq -r '.[0].href'
++ echo ''
+ DOWNLOAD_URL=
+ [[ -n '' ]]
+ for a in data-bi-prtid data-platform
++ jq -r '.[0].href'
++ restify --attribute=data-platform=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock/
++ echo ''
+ DOWNLOAD_URL=
+ [[ -n '' ]]
+ [[ '' =~ http.*/.*-(.*)\.zip ]]
++ head -1
++ ls 'bedrock_server-*'
+ [[ '' =~ bedrock_server-(.*) ]]
+ echo 'Failed to extract download URL '\'''\'' from https://www.minecraft.net/en-us/download/server/bedrock/'
+ cat restify.err
Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
2020/12/10 20:42:23 Failed to get from URLGet https://www.minecraft.net/en-us/download/server/bedrock/: x509: certificate is valid for ingress.local, not www.minecraft.net
+ rm restify.err
+ exit 2

**Comment by itzg** [comment]
Ah, I forgot that is failing during the initial step the restify tool I developed. It's developed in Go, so there's a slight chance it's getting DNS info incorrectly via what curl would resolve. 

Maybe I'll kick off a fresh build of restify with the newest Go compiler. I'll also see what debugs I can put in there. 

Meanwhile, I'm still thinking it's something about the kube DNS or ingress provider is confusing it. What kubernetes distro are you using and ingress proxy provider?

**Comment by RoyalDecline** [comment]
Just noticed bedrock_entry.sh does not list version 1.16.200.02  Could that be related ? 
Pretty standard install on Ubuntu.  Helm install of Nginx for ingress

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by itzg** [comment]
Can you add this environment variable to your pod:
```yaml
- name: GODEBUG
  value: "netdns=1"
```

[According to this](https://golang.org/pkg/net/#hdr-Name_Resolution), it should cause the `restify` run to output DNS resolving info.

**Comment by itzg** [comment]
...however, that might not help much, since all I get is

```
go package net: built with netgo build tag; using Go's DNS resolver
```

**Comment by RoyalDecline** [comment]
It seem to do as you expected. 

Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
go package net: built with netgo build tag; using Go's DNS resolver
2020/12/10 21:53:13 Failed to get from URLGet https://www.minecraft.net/en-us/download/server/bedrock/: x509: certificate is valid for ingress.local, not www.minecraft.net
+ rm restify.err
+ exit 2

**Comment by RoyalDecline** [comment]
Ok, i was able to fix it. I just have no idea why the fix is the fix.   I had to remove the wildcard from my DNS.  
I noticed it was hitting my webserver when running the restify command.  Almost like the DNS was searching domains before IPs when resolving.

**Comment by itzg** [comment]
Strange indeed, but I'm glad you found the fix.
