### ISSUE TITLE
documentation error (missing equals sign)

### ISSUE THREAD

**Issue by finndo77** [itzg/docker-minecraft-bedrock-server#119]
hi, I noticed on page:
[https://hub.docker.com/r/itzg/minecraft-bedrock-server](https://hub.docker.com/r/itzg/minecraft-bedrock-server)
under the whitelist section, you have this:
`-e WHITE_LIST_USERS "player1,player2,player3"`

please note that if you do not put an equals sign after USERS you will receive the following error:
```
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

thanks!

**Comment by itzg** [comment]
Good catch! That is indeed a typo.
