### ISSUE TITLE
Issues with downloading new server version - some suggestions and logs

### ISSUE THREAD

**Issue by potomato** [itzg/docker-minecraft-bedrock-server#123]
Hi,

I've been using this image for a while and it's been great, but has been intermittently failing to download the latest server version for a while. When this happens it seems to use the oldest version it has, rather than newest.

Attached are DEBUG logs from a successful and failed start. There's not much of a clue what's going on. It doesn't `cat restify.err` in this case. Also I think the `ls` would benefit from `-rv` to sort reverse numerically to get the true latest server version.
(I've removed some time values to help diffing and removed some usernames from one that whitelists).

I've got a local branch with these changes but don't have rights to push. Can fork if that would help.

Suggestions are:

1. bedrock_entry.sh line 50 to become `elif [[ $(ls -rv bedrock_server-* 2> /dev/null|head -1) =~ bedrock_server-(.*) ]]; then`
2. add new line `cat restify.err` after line 52 (`echo "WARN..`)
3. add some retry logic around the restify call so it tries 3 times with a short wait. If it's transient this may fix it, alternatively the `cat restify.err`  may give us some clues. 

[good_bedrock_start.txt](https://github.com/itzg/docker-minecraft-bedrock-server/files/5723868/good_bedrock_start.txt)
[failed_bedrock_start.txt](https://github.com/itzg/docker-minecraft-bedrock-server/files/5723869/failed_bedrock_start.txt)

Also would like to discuss cleanup of old versions. My volumes are getting pretty big and I think it keeps entire versions of old worlds, which can probably go after a while.

Thanks for everything!

**Comment by itzg** [comment]
A PR would be great and yes, you have to fork before you can PR into a repo without access rights.

**Comment by potomato** [comment]
Ok great I've forked, patched and built the image. I'll run it for a while and see how things go and raise a PR if/when I think it's improved things.
