### ISSUE TITLE
New area is showing empty

### ISSUE THREAD

**Issue by westchen1981** [itzg/docker-minecraft-bedrock-server#128]
Hi, this server works like a charm and thank you for your great project!

But I found that new area is showing empty, and it finally updated after few minutes.
Is this normal? Or is there anything I can do to shorten the update interval?

Thank you. 😊

**Comment by itzg** [comment]
Game engines like Minecraft's tend to do most processing on a single thread, so it sounds like a CPU core might be maxed out. Since docker containers are simply Linux processes, use `top` to check CPU usage when it's doing that.

**Comment by westchen1981** [comment]
Okay I see, looks like it's the case.
![Snipaste_2021-01-16_19-07-35](https://user-images.githubusercontent.com/77521251/104810266-4851ea80-582e-11eb-8130-176b8e1e4dda.png)

Since I ran the server on a 2-cores NAS, guess I would need a more powerful machine in the future. 😫

Thank you for your quick reply! 👍
