### ISSUE TITLE
Unable to start container with data volume

### ISSUE THREAD

**Issue by FloatingMilkshake** [itzg/docker-minecraft-bedrock-server#131]
I'm using Docker for Windows. Whenever I try to start the container, I get this:
```
DEBU[0000] Using /data to match uid and gid

DEBU[0000] Resolved UID=0 from match path

DEBU[0000] Resolved GID=0 from match path

Starting Bedrock server...

/opt/bedrock-entry.sh: line 127: /data/bedrock_server-1.16.201.02: Permission denied
```
I'm using Docker for Windows so I can't check permissions like you would on a Linux host.

The volume was copied from an archive file - not sure if that broke any permissions, but I don't know where to go from here. I'm not able to edit the permissions on the volume directly (NTFS permissions, I mean) as `docker-data` is mounted as a network location.

**Comment by itzg** [comment]
I primarily use Docker Desktop on Windows myself and just double checked that using a newly corrected directory for volume attachment works at least:

```
PS C:\> docker run -it --rm -e EULA=TRUE -v C:\bedrock-data:/data itzg/minecraft-bedrock-server
DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=0 from match path
DEBU[0000] Resolved GID=0 from match path
DEBU[0000] Forwarding signal                             signal="window changed"
Downloading Bedrock server version 1.16.201.02 ...
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2021-01-31 03:14:13 INFO] Starting Server
[2021-01-31 03:14:13 INFO] Version 1.16.201.2
```

Can you provide the exact command you used to create the container?

What version of Docker Desktop are you running? 

Are you using [the WSL2 backend](https://docs.docker.com/docker-for-windows/wsl/)? I'm using WSL2, but Hyper-V with volume mounts also used to work?

Can you replace the following with the same `-v` you're using and provide that file listing? 

```
docker run --rm -v C:\bedrock-data:/data --entrypoint bash itzg/minecraft-bedrock-server -c "ls -l"
```

**Comment by FloatingMilkshake** [comment]
> Can you provide the exact command you used to create the container?

Whoops, forgot to include that. Here it is:
```
docker run -d -it --name mc-bedrock-server -e EULA=TRUE -p 19132:19132/udp -v mc-bedrock-server:/data itzg/minecraft-bedrock-server
```
> What version of Docker Desktop are you running?

I'm running Docker Desktop version 3.1.0 (51484), Engine version 20.10.2.
> Are you using the WSL2 backend?

Yes.
> Can you replace the following with the same `-v` you're using and provide that file listing?

Sure, here it is:
```
PS C:\Users\FloatingMilkshake> docker run --rm -v mc-bedrock-server:/data --entrypoint bash itzg/minecraft-bedrock-server -c "ls -l"
total 359008
-rw-r--r--  1 root root       146 Jan 24 14:41 Dedicated_Server.txt
-rw-r--r--  1 root root 366639608 Dec 12 01:15 bedrock_server-1.16.201.02
-rw-r--r--  1 root root     22210 Dec 12 00:30 bedrock_server_how_to.html
drwxr-xr-x 11 root root      4096 Jan 19 22:00 behavior_packs
drwxr-xr-x  9 root root      4096 Jan 19 22:01 definitions
drwxr-xr-x  2 root root      4096 Jan 16 22:17 development_behavior_packs
drwxr-xr-x  2 root root      4096 Jan 16 22:17 development_resource_packs
drwxr-xr-x  2 root root      4096 Jan 16 22:17 development_skin_packs
drwxr-xr-x  4 root root      4096 Jan 19 22:01 internalStorage
-rw-r--r--  1 root root    878304 Dec 12 00:38 libCrypto.so
drwxr-xr-x  2 root root      4096 Jan 19 21:51 minecraftpe
-rw-r--r--  1 root root        85 Jan 16 21:26 permissions.json
drwxr-xr-x  2 root root      4096 Jan 19 21:51 premium_cache
-rw-r--r--  1 root root       580 Dec 12 00:30 release-notes.txt
drwxr-xr-x  4 root root      4096 Jan 19 22:01 resource_packs
-rw-r--r--  1 root root      3686 Jan 31 02:54 server.properties
drwxr-xr-x 14 root root      4096 Jan 19 22:01 structures
drwxr-xr-x  3 root root      4096 Jan 19 22:06 treatments
-rw-r--r--  1 root root      2774 Jan 24 14:10 valid_known_packs.json
-rw-r--r--  1 root root        83 Jan 16 22:26 whitelist.json
drwxr-xr-x  2 root root      4096 Jan 16 22:17 world_templates
drwxr-xr-x  3 root root      4096 Jan 19 22:01 worlds
```
This issue only started occurring after I reinstalled Windows then copied the volume out of a backup I made. Before reinstalling the container/server was working perfectly.

**Comment by itzg** [comment]
How did you populate the Docker named volume `mc-bedrock-server`? That volume is actually managed within WSL2's Linux context, so file permissions are actually real Linux file permissions.

One way to fix your setup is to enable the execute bit on the bedrock server using

```
docker run --rm -v mc-bedrock-server:/data --entrypoint bash itzg/minecraft-bedrock-server -c "chmod +x bedrock_server-1.16.201.02"
```

**Comment by FloatingMilkshake** [comment]
> How did you populate the Docker named volume `mc-bedrock-server`?

Originally, before I reinstalled Windows, I used `docker volume create mc-bedrock-server`. But, when I had to reinstall, I archived the volume folder (`\\wsl\docker-desktop-data\version-pack-data\community\docker\volumes\mc-bedrock-server`) with 7-Zip and stored the archive somewhere else, then after reinstalling I extracted the archive and copied the volume back to Docker's volumes directory. That's probably not the proper way of doing it so that probably broke some permissions, causing the "permission denied" error in my OP.

**Comment by itzg** [comment]
Yeah, backups from WSL2 land over to Windows land is always a bit interesting. I'm hoping that `chmod` fix will work for you.

**Comment by FloatingMilkshake** [comment]
Alright, I ran that `chmod` fix...and got a different error.
```
DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=0 from match path
DEBU[0000] Resolved GID=0 from match path
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2021-01-31 03:46:21 INFO] Starting Server
[2021-01-31 03:46:21 INFO] Version 1.16.201.2
[2021-01-31 03:46:21 INFO] Session ID 74072182-d518-4793-b913-ac9e0b80e961
[2021-01-31 03:46:21 INFO] Level Name: test
[2021-01-31 03:46:21 INFO] Game mode: 0 Survival
[2021-01-31 03:46:21 INFO] Difficulty: 0 PEACEFUL
[INFO] opening worlds/test/db
./bedrock_server-1.16.201.02: relocation error: ./bedrock_server-1.16.201.02: symbol  version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
```

**Comment by itzg** [comment]
Let's force it to redownload the server binary, so move the existing one out of the way with:

```
docker run --rm -v mc-bedrock-server:/data --entrypoint bash itzg/minecraft-bedrock-server -c "mv bedrock_server-1.16.201.02 bedrock_server-old"
```

and then try starting normally.
```

**Comment by FloatingMilkshake** [comment]
Awesome, it starts now! Thanks Geoff!
