### ISSUE TITLE
(Suggestion) Add Cloudburst Nukkit Support

### ISSUE THREAD

**Issue by LichLord91** [itzg/docker-minecraft-bedrock-server#133]
https://github.com/CloudburstMC/Nukkit

Nukkit is nuclear-powered server software for Minecraft: Bedrock. It has a few key advantages over other server software:

Written in Java, Nukkit is faster and more stable.
Having a friendly structure, it's easy to contribute to Nukkit's development and rewrite plugins from other platforms into Nukkit plugins.
Nukkit is under improvement yet, we welcome contributions.

**Comment by reslip1** [comment]
You can setup nukkitx easily in a container already with docker-compose. 

  nukkitx:
    container_name: nukkitx
    build:
      context: https://github.com/CloudburstMC/Nukkit.git
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 19132:19132 
      - 19132:19132/udp
    stdin_open: true
    tty: true

**Comment by itzg** [comment]
There's also a helm chart already provided:

https://github.com/CloudburstMC/Nukkit#kubernetes--helm

I'm going to close this issue since Nukkit was already going to be too much a deviation from the scope of the current repo.

**Comment by LichLord91** [comment]
> You can setup nukkitx easily in a container already with docker-compose.
> 
> nukkitx:
> container_name: nukkitx
> build:
> context: https://github.com/CloudburstMC/Nukkit.git
> dockerfile: Dockerfile
> restart: unless-stopped
> ports:
> - 19132:19132
> - 19132:19132/udp
> stdin_open: true
> tty: true

Yeah i saw they had their own, . itzg usually adds a bit more flair and configurable options in his setups so was curious if he wanted to add this to this repo or make a new one if the project was interesting enough.  Though I see its out of scope , no worries itzg. :) Ill just use theirs or make one myself if i get into it.
