### ISSUE TITLE
Container fails to pass health check

### ISSUE THREAD

**Issue by MrPotatoBobx** [itzg/docker-minecraft-bedrock-server#145]
Hello, I have deployed this container a few days ago and it was smooth sailing from there, until i decided to restart my machine, and now it spits this error at me:

`2021/04/23 04:48:43 failed to query bedrock server 127.0.0.1:19132: timeout reading the response: read udp 127.0.0.1:38201->127.0.0.1:19132: read: connection refused`

any ideas to what's going on? Thanks in advance

**Comment by Kaiede** [comment]
I think you are hitting #144 on the restart since the container is likely trying to update, and getting stuck waiting for user input on what files are safe to overwrite.

While it’s in this state, the container will be marked as unhealthy because the server hasn’t been started yet.  Marking it unhealthy in this state is the correct approach, IMO.

To confirm, you can use `docker logs` on the container to see what has been written to standard out. You can then use `docker attach` to attach to the container and provide input to the update script which will unblock the update and get the server started.

**Comment by MrPotatoBobx** [comment]
Yup, it was trying to update, thanks for the response, I wonder if there's any way to automate that

**Comment by itzg** [comment]
Yep, I can address that, but it's annoying/weird that Mojang let their build scripts leak into the distribution.

**Comment by peterm888** [comment]
I got this error when I had two containers running in docker net=host mode (for Lan Game to work, even if only partially).  Problem went away when only one container running.  Perhaps a clash in port usage somehow?

**Comment by itzg** [comment]
The latest image should now fix this.

**Comment by Oldman000** [comment]
Thank you for all your work on this. I was experiencing this issue as well. Now receive mv: cannot move 'behavior_packs' to 'backup-pre-1.16.221.01/behavior_packs': Directory not empty.

**Comment by itzg** [comment]
Oh, the previous, failed upgrade execution probably got it into a weird state. Removing `backup-pre-1.16.221.01` should fix it, but I'm also thinking I should have the backup logic remove, if present, the per-version backup destination.

**Comment by Oldman000** [comment]
Thanks, started over with backup copy. Progress stops at "Backing up world_templates into backup-pre-1.16.221.01". Will stay at version 1.16.210.06 for now. Thanks again for your work on this. Will try again later next week.

**Comment by itzg** [comment]
See if the latest image now fixes that.

**Comment by Oldman000** [comment]
Thank you for the quick response. I have tried to update using fresh backup, unfortunately still stuck at "Backing up world_templates into backup-pre-1.16.221.01". 

,Downloading Bedrock server version 1.16.221.01 ...
,Backing up behavior_packs into backup-pre-1.16.221.01
,Backing up minecraftpe into backup-pre-1.16.221.01
,Backing up resource_packs into backup-pre-1.16.221.01
,Backing up structures into backup-pre-1.16.221.01
,Backing up treatments into backup-pre-1.16.221.01
Backing up world_templates into backup-pre-1.16.221.01

**Comment by Oldman000** [comment]
Just FYI, I blew away my original load, started fresh with 221.01, and restored my world/server.properties, etc. without issue. Up and running. It could just be my system issue. So no problems on my end that need addressed. Thanks again for all you do.

**Comment by hakova** [comment]
Hi there,

I got hit by this issue today. My docker-compose.yaml file is essentially a clone of the example file and I am assuming it is downloading the latest image. It reports downloading the version 1.16.221.01 and gets stuck at that stage, which can be rescued as stated above by attaching to the container and providing input. I just wanted to report that this was still the case today although @itzg stated above that the latest image should have resolved it.

Thank you for providing and maintaining this great container!

**Comment by itzg** [comment]
@hakova can you provide the output of

```
docker image ls itzg/minecraft-bedrock-server
```

**Comment by hakova** [comment]
Here you go @itzg :

`$ docker image ls itzg/minecraft-bedrock-server`

`REPOSITORY                      TAG       IMAGE ID       CREATED        SIZE`
`itzg/minecraft-bedrock-server   latest    855b3e180bac   5 months ago   165MB`

**Comment by itzg** [comment]
@hakova That's a very old pull of the image. Pull the latest and that should work much better.

**Comment by hakova** [comment]
Indeed it did. Thanks!
