### ISSUE TITLE
Auto upgrade gets stuck at unzip

### ISSUE THREAD

**Issue by peterm888** [itzg/docker-minecraft-bedrock-server#146]
I am running a new install, with Bedrock v 1.16.220.02 and the upgrade to 1.16.221.01 is stuck at the unzip step (unzip process is present but not doing anything).  Restarting the container just does the same thing.  If this cannot be fixed immediately, can I disable upgrade mechanism for now?

**Comment by peterm888** [comment]
I am running the container under it's own user account (non-root).  Minecraft is working correctly before the upgrade attempt started.

**Comment by itzg** [comment]
Hmm, that's strange unzip would get stuck. Anything special about the file system attached to the container's `/data`?

As far as disabling the upgrade, if you set `VERSION` to match the one already present then it would skip the upgrade however at this point some of that version's files would be moved aside.

**Comment by peterm888** [comment]
Yes, I have been debugging.  The unzip works fine into a sub-directory, but not into the /data folder.  I want to run as a non-root user, and have the uid/gid set correctly (same as reported by the application).  Docker "persistent volumes" don't allow this, so I'm using directly mapped filesystem (/var/lib/volumes/minecraftdata:/data).  I'm checking further.

**Comment by itzg** [comment]
Actually I wonder if it's the same issue as #144 and #145. I'm going to work on a fix for that shortly.

**Comment by itzg** [comment]
See if the latest image fixes this for you.

**Comment by peterm888** [comment]
The prior behaviour was to overwrite all files except the config .json ones.  Using the unzip flags '-o -q -x ...' may be a better option, where -o does the overwrite without prompting.

**Comment by itzg** [comment]
I decided on the safer of the two options since I already had logic to move away files and directories to be replaced.

**Comment by peterm888** [comment]
The files which need to be protected from overwrite (*.json) were fine with the "-x" (and worlds data is not overwritten anyway, is it?) ... but the huge number of other files in the bedrock release surely should overwrite the existing versions, in case code change needs those files changed too.  Of course, I don't know if a player can change these? Actually, since overwriting does not remove now-redundant files, would a move/create-new approach be better overall?  But than would mean re-loading any resource packs/files etc ... there is no "simple" fully correct answer here I think. 

And I think the prior bedrock application binary is not removed at the moment as well.

**Comment by itzg** [comment]
What about the code above the comment I had there?

https://github.com/itzg/docker-minecraft-bedrock-server/blob/a8aa3846dafbb8aa764dd5f0a04720db2f84c791/bedrock-entry.sh#L85-L96

**Comment by itzg** [comment]
...and the "remove files to upgrade" strategy simplified the ability to reconcile removal of files from upgraded/downgraded versions since an `unzip -o -x` approach would always be additive.

**Comment by wormiedk** [comment]
I had the same issue. Running without -d in the command allowed me to overwrite the files. After fixing I closed the container and rebooteed with -d

**Comment by itzg** [comment]
@peterm888 are you ok with the approach after I provided more context for the decision?

**Comment by shmilyoo** [comment]
```
minecraft-survival | + rm -rf bedrock_server '*.so' release-notes.txt bedrock_server_how_to.html valid_known_packs.json premium_cache
minecraft-survival | + bkupDir=backup-pre-1.16.221.01
minecraft-survival | + for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
minecraft-survival | + '[' -d behavior_packs ']'
minecraft-survival | + for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
minecraft-survival | + '[' -d definitions ']'
minecraft-survival | + for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
minecraft-survival | + '[' -d minecraftpe ']'
minecraft-survival | + for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
minecraft-survival | + '[' -d resource_packs ']'
minecraft-survival | + for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
minecraft-survival | + '[' -d structures ']'
minecraft-survival | + for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
minecraft-survival | + '[' -d treatments ']'
minecraft-survival | + for d in behavior_packs definitions minecraftpe resource_packs structures treatments world_templates
minecraft-survival | + '[' -d world_templates ']'
minecraft-survival | ++ ls server.properties whitelist.json permissions.json
minecraft-survival | + unzip -q /tmp/bedrock-server-1.16.221.01.zip -x permissions.json server.properties whitelist.json
```

same issue. stuck here

**Comment by shmilyoo** [comment]
@peterm888 any progress?
