### ISSUE TITLE
old bedrock_server files in docker-volume

### ISSUE THREAD

**Issue by zordaz** [itzg/docker-minecraft-bedrock-server#150]
When upgrading to a new version of docker-minecraft-bedrock-server, the old serverfiles are left behind in the volume, even after remove the image itself. Is this by design? This can take up a considerable amount of space:

drwxr-xr-x  9 root root 4,0K dec  1 08:16 backup-pre-1.16.101.01
drwxr-xr-x  9 root root 4,0K aug 17  2020 backup-pre-1.16.20.03
drwxr-xr-x  9 root root 4,0K dec 20 14:18 backup-pre-1.16.201.02
drwxr-xr-x  9 root root 4,0K mei  2 21:46 backup-pre-1.16.221.01
drwxr-xr-x  9 root root 4,0K sep  4  2020 backup-pre-1.16.40.02
-rwxr-xr-x  1 root root 174M apr 13  2020 bedrock_server-1.14.60.5
-rwxr-xr-x  1 root root 348M nov 20 04:11 bedrock_server-1.16.101.01
-rwxr-xr-x  1 root root 266M jun 26  2020 bedrock_server-1.16.1.02
-rwxr-xr-x  1 root root 266M jul 31  2020 bedrock_server-1.16.20.03
-rwxr-xr-x  1 root root 350M dec 12 02:15 bedrock_server-1.16.201.02
-rwxr-xr-x  1 root root  66M apr 15 04:14 bedrock_server-1.16.221.01
-rwxr-xr-x  1 root root 266M sep  3  2020 bedrock_server-1.16.40.02

**Comment by itzg** [comment]
That's very true, the size of those quickly adds up. Maybe I'll put the backup in `/tmp` since that would go away when the container restarts.

**Comment by itzg** [comment]
The latest image will now place the upgrade backup in `/tmp` and removes any existing backup directories.

**Comment by double16** [comment]
In the situation where the new server version fails to start and the container stop or restarts, doesn’t that make the backup inaccessible? IMHO, it was better to clean up the backups myself when I was confident the latest version worked.

**Comment by itzg** [comment]
It does, but there's nothing really worth recovering. I'm only making the backup of the files provided by Mojang out of paranoia there might be user content in there.

Can the two of you please vote whether you want me to change this or not or what I should do as a compromise?

**Comment by zordaz** [comment]
Only keep one old version instead of all?

**Comment by double16** [comment]
You're saying you couldn't put back the backup-pre* files to revert to an older version?

**Comment by zordaz** [comment]
Are we only talking about the backup-pre* files, or also about the old bedrock_server files as well? Especially those old bedrock_server files are rather big. The backup-pre files are aprox 30MB each afaik.

**Comment by itzg** [comment]
> You're saying you couldn't put back the backup-pre* files to revert to an older version?

That wasn't what I was saying. Have you ever needed to recover those particular backup directories?

**Comment by itzg** [comment]
> Only keep one old version instead of all? 

Ok, it'll take more effort but I can do that. PRs are welcome too.

**Comment by double16** [comment]
> > You're saying you couldn't put back the backup-pre* files to revert to an older version?
> 
> That wasn't what I was saying. Have you ever needed to recover those particular backup directories?

I haven't recovered the files in the backup-pre* directory but I have done a recovery of the same files in the root. It wasn't because of a version upgrade problem, but recovering old files does work. The thing about backups is you hope you never need them, but you are glad to have them when you do.

**Comment by double16** [comment]
> > Only keep one old version instead of all?
> 
> Ok, it'll take more effort but I can do that. PRs are welcome too.

Sorry I don't have much time for a PR right now, but in the past I've used `find` with `-mtime` to delete files older than a certain number of days. So instead of only the last one, maybe only keep for 10 days or similar. One should know by then if it's working.

**Comment by itzg** [comment]
I reverted the change for now and I'll fix it when I get another chance.

**Comment by itzg** [comment]
Let's try that again... now there's a variable `PACKAGE_BACKUP_KEEP` (default is 2) to specify how many package-backups to keep

https://github.com/itzg/docker-minecraft-bedrock-server#container-specific

**Comment by zordaz** [comment]
On my systems this works.
