### ISSUE TITLE
Update for future versions

### ISSUE THREAD

**Issue by Felipenho** [itzg/docker-minecraft-bedrock-server#152]
Hello!

I Would like to update the server to the new update 1.17.0 but it seems is too recent.
There is any way to identify when a new version comes out and then download it?

Thank you!

![image](https://user-images.githubusercontent.com/28564341/121399778-2831dd80-c92d-11eb-9c3c-ba15e81742e1.png)

**Comment by itzg** [comment]
On container startup it pulls the latest, which worked fine for me just now:

```
> docker run -it --rm -e EULA=TRUE itzg/minecraft-bedrock-server


DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
DEBU[0000] Forwarding signal                             signal="window changed"
Downloading Bedrock server version 1.17.0.03 ...
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2021-06-09 17:54:52 INFO] Starting Server
[2021-06-09 17:54:52 INFO] Version 1.17.0.03
[2021-06-09 17:54:52 INFO] Session ID d2316770-de22-4fc2-b4c2-669ab4b2de1f
[2021-06-09 17:54:52 INFO] Level Name: Bedrock level
[2021-06-09 17:54:52 INFO] Game mode: 0 Survival
[2021-06-09 17:54:52 INFO] Difficulty: 1 EASY
[INFO] opening worlds/Bedrock level/db
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 not supported
[INFO] IPv4 supported, port: 41465
[INFO] IPv6 not supported
[INFO] Server started.
```

**Comment by itzg** [comment]
...as far as detecting a new version and auto-restarting the container (if that's what you're asking), then that's beyond the scope of this image. It would be great if someone would implement a sidecar image/utility that could automate that.

**Comment by Felipenho** [comment]
Thank you very much!
That solved the problem, I'll try to replicate an internal CICD to try something out
