### ISSUE TITLE
How do I adjust the permissions for groups?

### ISSUE THREAD

**Issue by bmf** [itzg/docker-minecraft-bedrock-server#153]
Apologies if this is the wrong forum as I don't think this is an issue with the server per se.  Can someone please point me to some instructions on how to change the granular permissions for groups from the docker-compose.yml? Specifically, I want to change my members group so they cannot hit other players. Thank you in advance for your help!

**Comment by itzg** [comment]
I don't think that aspect can be controlled by the docker image / compose file itself. These are the server properties that can be configured

https://minecraft.fandom.com/wiki/Server.properties#Bedrock_Edition_3

**Comment by Patchoulino** [comment]
there's no pvp option on server.properties for bedrock, it's a gamerule

/gamerule pvp false
https://minecraft.fandom.com/wiki/Game_rule

**Comment by itzg** [comment]
Thanks @Patchoulino ! I'm going to close this out, but can discuss further if needed.

**Comment by bmf** [comment]
Apologies to @itzg and @Patchoulino, I should have closed this when I got my answer in June. Thank you both for the follow up!
