### ISSUE TITLE
Failed to extract download URL

### ISSUE THREAD

**Issue by peternixon** [itzg/docker-minecraft-bedrock-server#155]
When I try to run to container I get:

Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
Unable to find an element with attribute matcher data-platform=serverBedrockLinux

Is this due to a change on the website?

**Comment by raver00999** [comment]
> When I try to run to container I get:
> 
> Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
> Unable to find an element with attribute matcher data-platform=serverBedrockLinux
> 
> Is this due to a change on the website?

Same issue here.

**Comment by peternixon** [comment]
OK. So it turns out that I can get it to work if I force the version like this:
docker run -d -it -e EULA=TRUE -e VERSION="1.17.2.01" --name "minecraft" -p 19132:19132/udp itzg/minecraft-bedrock-server

**Comment by itzg** [comment]
> Is this due to a change on the website?

Ugh, yes it is. They changed the DOM element attribute that the script used. I think I see a new one that'll work...

**Comment by itzg** [comment]
Crap, it's even worse -- they're preventing programmatic access to the page:

```
 curl https://www.minecraft.net/en-us/download/server/bedrock/
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;www&#46;minecraft&#46;net&#47;en&#45;us&#47;download&#47;server&#47;bedrock&#47;" on this server.<P>
Reference&#32;&#35;18&#46;3d382f17&#46;1625237942&#46;11920e6e
</BODY>
</HTML>
```

**Comment by double16** [comment]
You can make the curl command look like a browser request. If you need help with that let me know.

**Comment by itzg** [comment]
With `user-agent` header? Yep, was just exploring that and seems to resolve it.

**Comment by itzg** [comment]
...good news is that it is happy with any user agent value, so I can provide a genuine indication of the image's access rather than faking a browser's user agent.

**Comment by itzg** [comment]
Published a new image that includes the fix for this.

**Comment by shrike2004** [comment]
Got image:latest and still get:

Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock
2021/07/05 07:49:45 Unable to find an element with attribute matcher data-bi-prtid=serverBedrockLinux

**Comment by sheepa** [comment]
> Got image:latest and still get:
> 
> Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock
> 2021/07/05 07:49:45 Unable to find an element with attribute matcher data-bi-prtid=serverBedrockLinux

Same for me, seems they updated it again..

**Comment by hantusk** [comment]
@sheepa @shrike2004 it works again, make sure you run `docker pull itzg/minecraft-bedrock-server` to pull the latest image before running (or add `--pull always` to your docker run command)

**Comment by sheepa** [comment]
@hantusk I have the latest ie sha256:06a287204b42 - when i pull it it says "Status: Image is up to date for itzg/minecraft-bedrock-server:latest" and I still get the error.

**Comment by itzg** [comment]
What does `docker inspect <<your container name>> -f "{{.Image}}"` report? I think you'll need to recreate the container to force the newly pulled image to be used. I use docker compose to avoid all that hassle.

**Comment by trilliam25** [comment]
I can't get any download of the 1.17 server even after pulling. Not even from a new container created by @peternixon 's command

**Comment by itzg** [comment]
@trilliam25 provide the output of

```
docker pull itzg/minecraft-bedrock-server
```

and the output of

```
docker run -it --rm -e EULA=TRUE -e DEBUG=true itzg/minecraft-bedrock-server
```

**Comment by amex4152** [comment]
I see the tag that identifies the element different. Attached image to show

![BedrockDocker](https://user-images.githubusercontent.com/5400302/125330510-7cedbd00-e30c-11eb-84fd-4e92f3e28e17.png)

**Comment by sheepa** [comment]
> docker inspect <<your container name>> -f "{{.Image}}"

`sha256:f169fdb04691d6dbd986f000f678e4863d503b178c2f0446dc2bbd7418184824`

This is after running:

```
docker pull itzg/minecraft-bedrock-server
Using default tag: latest
latest: Pulling from itzg/minecraft-bedrock-server
Digest: sha256:12afdd4bcf9b827744e1193aee0fd2981c06933844e223193f49b7a3e858cd35
Status: Image is up to date for itzg/minecraft-bedrock-server:latest
docker.io/itzg/minecraft-bedrock-server:latest
```

Still same error:

```
Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock
2021/07/12 17:31:12 Unable to find an element with attribute matcher data-bi-prtid=serverBedrockLinux
```

**Comment by shrike2004** [comment]
> @trilliam25 provide the output of
> 
> ```
> docker pull itzg/minecraft-bedrock-server
> ```
> 
> and the output of
> 
> ```
> docker run -it --rm -e EULA=TRUE -e DEBUG=true itzg/minecraft-bedrock-server
> ```

![Bserror](https://user-images.githubusercontent.com/28308992/125332813-2c00b780-e352-11eb-8e04-6a4db9c0e31d.PNG)

**Comment by itzg** [comment]
The pulled image ID is indeed correct, so it's very strange since it continues to work fine for me (and I'm guessing many other people):

```
PS C:\Users\itzg> docker pull itzg/minecraft-bedrock-server
Using default tag: latest
latest: Pulling from itzg/minecraft-bedrock-server
0bc3020d05f1: Already exists
a6ca0c08033c: Already exists
79ec4277d8f6: Already exists
6682482e88eb: Already exists
3f0cac26a0c4: Already exists
c062ee00f74b: Already exists
08a993ff9556: Already exists
13eae6fcbb53: Already exists
fcebe7d1b8d2: Already exists
31f7da4fbf23: Already exists
ab55dc2970f4: Already exists
Digest: sha256:12afdd4bcf9b827744e1193aee0fd2981c06933844e223193f49b7a3e858cd35
Status: Downloaded newer image for itzg/minecraft-bedrock-server:latest
docker.io/itzg/minecraft-bedrock-server:latest
PS C:\Users\itzg> docker run -it --rm -e EULA=TRUE -e DEBUG=true itzg/minecraft-bedrock-server
DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=0 from match path
DEBU[0000] Resolved GID=0 from match path
+ curlArgs=(-v)
++ id -a
++ ls -ld /data
+ echo 'DEBUG: running as uid=0(root) gid=0(root) groups=0(root) with drwxr-xr-x 2 root root 4096 Jul  2 20:24 /data'
DEBUG: running as uid=0(root) gid=0(root) groups=0(root) with drwxr-xr-x 2 root root 4096 Jul  2 20:24 /data
+ downloadPage=https://www.minecraft.net/en-us/download/server/bedrock
+ [[ TRUE != TRUE ]]
+ case ${VERSION^^} in
+ for a in data-platform data-bi-prtid
+ for i in {1..3}
++ restify --user-agent=itzg/minecraft-bedrock-server --attribute=data-platform=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock
++ jq -r '.[0].href'
DEBU[0000] Forwarding signal                             signal="window changed"
+ DOWNLOAD_URL=https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.2.01.zip
,
,
,
```

**Comment by itzg** [comment]
To further debug, provide the output of this command:

```
docker run -it --rm --entrypoint bash itzg/minecraft-bedrock-server -c "curl -H 'user-agent: itzg/restify' -H 'accept: */*' https://www.minecraft.net/en-us/download/server/bedrock | grep serverBedrockLinux"
```

**Comment by sheepa** [comment]
This is the output from that command, removing the grep..

```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;www&#46;minecraft&#46;net&#47;en&#45;us&#47;download&#47;server&#47;bedrock" on this server.<P>
Reference&#32;&#35;18&#46;6c931602&#46;1626135471&#46;247de
</BODY>
</HTML>
```

I have tried this from multiple OVH ips and get the same result.. however when i run it from my home connection it just hangs.. Looks like a blacklist and then maybe a botcheck that fails with a simple curl if not blacklisted..

**Comment by itzg** [comment]
Just to make sure, you included the `-H 'user-agent: itzg/restify' -H 'accept: */*'` arguments within that curl invocation?

**Comment by sheepa** [comment]
Hello, yes I did, I did some testing and in order to get a proper response everywhere I need to run 

`curl "https://www.minecraft.net/en-us/download/server/bedrock" -H "user-agent: itzg/restify" -H "accept-language: *" --compressed`

It needs:

- User agent to be sent and include a slash (/)
- Accept-language to be set
- The --compressed flag

If you remove any of the three i get permission denied

**Comment by achton** [comment]
> If you remove any of the three i get permission denied

@sheepa Are you sure about that conclusion? From my tests, it seems that their Akamai network blocks only clients that do not provide a user-agent string, or provide an unknown or fake user-agent. The other options are not affecting whether I get a 403 or not.

This returns a HTTP 200 (`-A` is another way of asking curl to set the user-agent header) :
```bash
curl --verbose --silent -A "itzg/restify" https://www.minecraft.net/en-us/download/server/bedrock -O /dev/null
```

This returns a HTTP 403:
```bash
curl --verbose --silent -A "horsey" https://www.minecraft.net/en-us/download/server/bedrock -O /dev/null
```

**Comment by sheepa** [comment]
> > If you remove any of the three i get permission denied
> 
> @sheepa Are you sure about that conclusion? From my tests, it seems that their Akamai network blocks only clients that do not provide a user-agent string, or provide an unknown or fake user-agent. The other options are not affecting whether I get a 403 or not.
> 
> This returns a HTTP 200 (`-A` is another way of asking curl to set the user-agent header) :
> 
> ```shell
> curl --verbose --silent -A "itzg/restify" https://www.minecraft.net/en-us/download/server/bedrock -O /dev/null
> ```
> 
> This returns a HTTP 403:
> 
> ```shell
> curl --verbose --silent -A "horsey" https://www.minecraft.net/en-us/download/server/bedrock -O /dev/null
> ```

Both of those return 403 for me.

**Comment by itzg** [comment]
I'm cooking up an idea for a little web service that will cache the latest bedrock version lookup. In the meantime just wanted to remind those with this issue that you can manually specify VERSION.

**Comment by MattrCoUk** [comment]
When I download the bedrock-server file manually and drop it in the data directory,
renaming and checking file perms that happens:

		WARN Minecraft download page failed, so using existing download of 1.17.10.04.zip

		2021/07/14 07:00:33 Failed to get from URLGet https://www.minecraft.net/en-us/download/server/bedrock/: dial tcp: lookup www.minecraft.net on 127.0.0.11:53: read udp 127.0.0.1:39132->127.0.0.11:53: i/o timeout

		Starting Bedrock server...

		/opt/bedrock-entry.sh: line 147: /data/bedrock_server-1.17.10.04.zip: Permission denied
		
		
any clues?

Also is it possible to change the download url to e. g. my own url or even localhost?

**Comment by achton** [comment]
@MattrCoUk See the [README](https://github.com/itzg/docker-minecraft-bedrock-server#environment-variables) - you provide `VERSION` as an env variable and let the container download the version you want, e.g.:

```bash
$ docker run -it --name minecraft \
  -e EULA=TRUE \
  -e VERSION="1.17.10.04" \
  -p 19132:19132/udp \
  itzg/minecraft-bedrock-server

DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
Downloading Bedrock server version 1.17.10.04 ...
DEBU[0000] Forwarding signal                             signal="window changed"
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2021-07-14 08:00:11 INFO] Starting Server
[2021-07-14 08:00:11 INFO] Version 1.17.10.04
[2021-07-14 08:00:11 INFO] Session ID 5bd6c21f-1395-4796-8dbb-acc731aa14fe
[2021-07-14 08:00:11 INFO] Level Name: Bedrock level
[2021-07-14 08:00:11 INFO] Game mode: 0 Survival
[2021-07-14 08:00:11 INFO] Difficulty: 1 EASY
[INFO] opening worlds/Bedrock level/db
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 not supported
[INFO] IPv4 supported, port: 56783
[INFO] IPv6 not supported
[INFO] Server started.
```

Also, that should work regardless of the original issue that people are having here, which is about downloading the **latest** version of the server automatically. So not related to this issue, really.

**Comment by MattrCoUk** [comment]
I was hoping thad downloading it manually and dropping in the folder will be a workaround to the automatic download failing.

**Comment by MattrCoUk** [comment]
Actually it worked with the older server version, guess there is something wrong with the server file downloaded manually.

**Comment by MattrCoUk** [comment]
By some unknown conincedence the server downloaded the backup automatically and starter-up correctly.

		Downloading Bedrock server version 1.17.10.04 ...
		DEBU[0030] Forwarding signal                             signal="window changed"
		DEBU[0030] Forwarding signal                             signal="window changed"
		Backing up behavior_packs into backup-pre-1.17.10.04
		Backing up definitions into backup-pre-1.17.10.04
		Backing up minecraftpe into backup-pre-1.17.10.04
		Backing up resource_packs into backup-pre-1.17.10.04
		Backing up structures into backup-pre-1.17.10.04
		Backing up treatments into backup-pre-1.17.10.04
		Backing up world_templates into backup-pre-1.17.10.04
		Starting Bedrock server...
		NO LOG FILE! - setting up server logging...
		[2021-07-14 09:34:59 INFO] Starting Server
		[2021-07-14 09:34:59 INFO] Version 1.17.10.04

What Ive noticed the size of the server downloaded by the script is larger than the one I’ve downloaded manually from the website. 🤷‍♂️

**Comment by tgckpg** [comment]
I just ran into this issue and it seems they have changed their download page subtly.
```
2021/07/14 09:57:30 Unable to find an element with attribute matcher data-bi-prtid=serverBedrockLinux
```
![image](https://user-images.githubusercontent.com/5273654/125606292-743d5464-eda2-487d-a3b0-9c5f5b830b2c.png)
As you can see the `data-bi-prtid` is no longer there now.

**Comment by tgckpg** [comment]
ok this is funny. I've accidentally discovered some working user-agent string when I mistakenly copy and pasted the wrong text.

**I'm installing it thru helm and `kubectl exec -it` directly into the pod then running the restify & curl command. The 200 ones restify can actually produce output.** 

Heres my journey

| Status Code | Name                                                                                                                |
|-------------|---------------------------------------------------------------------------------------------------------------------|
| 403         | itzg/minecraft-bedrock-server                                                                                       |
| 403         | itzg/restify                                                                              |
| 403         | Test                                                                                                                |
| 403         | abc                                                                                                                 |
| 403         | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0                                      |
| 403         | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 |
| 200         | https://www.minecraft.net/en-us/download/server/bedrock                                                             |
| 200         | www.minecraft.net                                                                                                   |
| 200         | www.minecraft                                                                                                       |
| 403         | minecraft                                                                                                           |
| 403         | minecraft?                                                                                                          |
| 403         | minecraft!                                                                                                          |
| 403         | .minecraft                                                                                                          |
| 403         | minecraft.                                                                                                          |
| 403         | www                                                                                                                 |
| 403         | www.                                                                                                                |
| 200         | www.mine                                                                                                            |
| 200         | www.min                                                                                                             |
| 200         | www.mi                                                                                                              |
| 200         | www.m                                                                                                               |
| 403         | w.m                                                                                                                 |
| 403         | ww.m                                                                                                                |

The shortest string that hit seems to be `www.m`. Hopefully they won't patch this. 😂

**Comment by itzg** [comment]
> I was hoping thad downloading it manually and dropping in the folder will be a workaround to the automatic download failing.

No, it won't. Set the VERSION environment variable like I said.

**Comment by claine-d** [comment]
Setting the variable in my docker-compose.yml file like this:

```
version: '3.4'

services:
  bds:
    container_name: mc
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      VERSION: "1.17.10.04"
      GAMEMODE: survival
      DIFFICULTY: hard
      VIEW_DISTANCE: 32
      ALLOW_CHEATS: "false"
      DEFAULT_PERMISSION_LEVEL: "Operator"
      SHOWCOORDINATES: "true"
      WHITE_LIST: 
    ports:
      - 19132:19132/udp
    volumes:
      - .:/data
    restart: always
    stdin_open: true
    tty: true
```

after pulling the latest container I try 

`sudo docker-compose up bds`

I get the following error message:

```
Downloading Bedrock server version 1.17.10.04 ...
mc                    | curl: (6) Could not resolve host: minecraft.azureedge.net
mc                    | ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.10.04.zip
mc                    |       Double check that the given VERSION is valid
mc exited with code 2
```

I'm able to download the file manually using the url listed above.  

If I used LATEST in the docker compose file I get a different type of error.  

```
 WARN Minecraft download page failed, so using existing download of 1.17.1.01
mc    | 2021/07/14 20:02:09 Failed to get from URLGet "https://www.minecraft.net/en-us/download/server/bedrock": dial tcp: lookup www.minecraft.net on 127.0.0.11:53: read udp 127.0.0.1:55190->127.0.0.11:53: i/o timeout
mc    | Starting Bedrock server...
```
what is the 127.0.0.11 mentioned?

Is this my network or something else?

**Comment by claine-d** [comment]
I thought I was running in host mode by default.  However specifying it in the docker-compose file like this

    `network_mode: host`

corrected my issue.  Using 'Latest' is working for me again and it didn't impact the multiple instances I have running on the same server.

**Comment by itzg** [comment]
I pushed an image update that increases the retry count and adds a delay between retries. It's a long-shot, but wondering if that might fix the 403's since they a little bit intermittent.

**Comment by sheepa** [comment]
> I pushed an image update that increases the retry count and adds a delay between retries. It's a long-shot, but wondering if that might fix the 403's since they a little bit intermittent.

The error is not intermittent. It either works on a specific machine or doesnt, might be ip / geo related. What works is the specific  params to curl in my last reply.

**Comment by itzg** [comment]
Now the latest image adds the `accept-language: *` header and the compressed behavior should have already been present.

**Comment by MattrCoUk** [comment]
It has always been like that for me tbh (have been using this repo for over a year).  The download usually gets through after 3–10 minutes of retries (im using docker-compose so the container restarts automatically). Only recently it has gone worse. I’ve disabled the ipv6 but can’t tell whether that helps or not. Using a Mac os high-sierra in UK on O2 broadband.

**Comment by sheepa** [comment]
> Now the latest image adds the `accept-language: *` header and the compressed behavior should have already been present.

It works now! Thanks!

**Comment by del-007** [comment]
I am still unable to download message.

DEBU[0000] Using /data to match uid and gid


DEBU[0000] Resolved UID=0 from match path

DEBU[0000] Resolved GID=0 from match path


WARN Minecraft download page failed, so using existing download of 1.17.0.03


2021/07/17 00:06:09 Unable to find an element with attribute matcher data-platform=serverBedrockLinux


Starting Bedrock server...


NO LOG FILE! - setting up server logging...

[2021-07-17 00:06:09 INFO] Starting Server

[2021-07-17 00:06:09 INFO] Version 1.17.0.03

In the earlier threads it was mentioned run the following command to debug parsing the download page.  This is what I am getting
docker run -it --rm --entrypoint bash itzg/minecraft-bedrock-server -c "curl -H 'user-agent: itzg/restify' -H 'accept: */*' https://www.minecraft.net/en-us/download/server/bedrock | grep serverBedrockLinux"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                        <a href="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.10.04.zip" aria-label="Download Ubuntu Server software for Ubuntu" class="btn btn-disabled-outline mt-4 downloadlink" role="button" data-platform="serverBedrockLinux" tabindex="-1">Download </a>
100  303k    0  303k    0     0   262k      0 --:--:--  0:00:01 --:--:--  262k

**Comment by del-007** [comment]
`docker run -it --rm --entrypoint bash itzg/minecraft-bedrock-server -c "curl -H 'user-agent: itzg/restify' -H 'accept: */*' https://www.minecraft.net/en-us/download/server/bedrock | grep serverBedrockLinux"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                        <a href="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.10.04.zip" aria-label="Download Ubuntu Server software for Ubuntu" class="btn btn-disabled-outline mt-4 downloadlink" role="button" data-platform="serverBedrockLinux" tabindex="-1">Download </a>
100  303k    0  303k    0     0   262k      0 --:--:--  0:00:01 --:--:--  262k`

**Comment by itzg** [comment]
I have now implemented a fallback mechanism for looking up the latest download URL. If you were still having issues, please re-pull the latest image and try now.

**Comment by del-007** [comment]
I re-pulled the latest image, and still getting the same error
2021/07/17 02:02:37 Unable to find an element with attribute matcher data-platform=serverBedrockLinux

**Comment by itzg** [comment]
@del-007 add `DEBUG=true` since that isn't the final output I expected from the latest image

**Comment by del-007** [comment]
How would I edit\add to an existing docker container?  I created mine without docker compose.
(I googled on how to edit and existin config and found this command
docker run -it -v /var/lib/docker:/var/lib/docker alpine vi $(docker inspect --format='/var/lib/docker/containers/{{.Id}}/config.v2.json' <container_id>), but i don't understand the .json layout on where to add that.

**Comment by MightyDunamis** [comment]
Hi itzg.  This particular change Microsoft did seems to have you busy. I really apricate the level of effort you have provided. I am also interested to know how to leverage the updated image against and existing container. I am able to create new containers that work without issue but my existing container/server is still unable to connect. Alternatively, if you know how to copy world data from one container to another that would serve as an alternate solution.

**Comment by del-007** [comment]
> Hi itzg. This particular change Microsoft did seems to have you busy. I really apricate the level of effort you have provided. I am also interested to know how to leverage the updated image against and existing container. I am able to create new containers that work without issue but my existing container/server is still unable to connect. Alternatively, if you know how to copy world data from one container to another that would serve as an alternate solution.

I was able to create a new container using the previous container data.  When you create your new container add the following argument
-v <existing_volume_name>:/data
I don't think this is copying the world per se.  Also i stopped my existing older container before starting up a new one pointing the previous container volume name.

**Comment by itzg** [comment]
> Hi itzg. This particular change Microsoft did seems to have you busy. I really apricate the level of effort you have provided. I am also interested to know how to leverage the updated image against and existing container. I am able to create new containers that work without issue but my existing container/server is still unable to connect. Alternatively, if you know how to copy world data from one container to another that would serve as an alternate solution.

First of all, I really appreciate your appreciation. This issue they caused has indeed required much more effort than is typical.

As for re-using the data volume, @del-007 's approach works and I also have a section in the java edition docs about converting an anonymous volume to a named one

https://github.com/itzg/docker-minecraft-server#converting-anonymous-data-volume-to-named-volume

**Comment by SuperMike3003** [comment]
Hi itzg, 
I also ran into this with the latest tag inside Docker Desktop with a persistent volume mounted.
Stopped and removed the container, ran docker pull with the latest tag, which then downloaded successfully.
I was then able to start a container normally.

**Comment by MightyDunamis** [comment]
> > Hi itzg. This particular change Microsoft did seems to have you busy. I really apricate the level of effort you have provided. I am also interested to know how to leverage the updated image against and existing container. I am able to create new containers that work without issue but my existing container/server is still unable to connect. Alternatively, if you know how to copy world data from one container to another that would serve as an alternate solution.
> 
> First of all, I really appreciate your appreciation. This issue they caused has indeed required much more effort than is typical.
> 
> As for re-using the data volume, @del-007 's approach works and I also have a section in the java edition docs about converting an anonymous volume to a named one
> 
> https://github.com/itzg/docker-minecraft-server#converting-anonymous-data-volume-to-named-volume

Thanks so much for sending me the link.  That did the trick.  I was able to create a new container and connect it to my old container's data.  I really appreciate it...sending coffee your way
