### ISSUE TITLE
Question: does this server alleviate the need for GeyserMC?

### ISSUE THREAD

**Issue by juanuys** [itzg/docker-minecraft-bedrock-server#162]
Hello, I have a quick question. I searched both this repo and the [other one ](https://github.com/itzg/docker-minecraft-server)for "geysermc" and found no results.

Does this server alleviate the need for using GeyserMC with the regular Minecraft server?
https://geysermc.org/

Regards,

**Comment by itzg** [comment]
No, GeyserMC is still applicable and in fact eliminates the need to run this bedrock image. Instead, you could run geyser in front of the java edition container and enable access from both client types.

**Comment by juanuys** [comment]
That's great, thank you :)
