### ISSUE TITLE
Can't find configuration properties on a Synology NAS

### ISSUE THREAD

**Issue by keepsmilyn** [itzg/docker-minecraft-bedrock-server#166]
Where are the configuration properties stored when this is installed on a Synology NAS? 

Each "container' sub-folder under Docker is empty. eg: \volume1\docker\ (sub folders)

**Comment by itzg** [comment]
Please ask in the Discord channel since I have no experience with NAS systems and cannot offer support beyond this image itself.

**Comment by keepsmilyn** [comment]
It all has to do with what folder you select to save this into. Be sure to use /home or /homes so that when it first launches it auto-generates all the subfolders in a visible folder on your Synology NAS server. 

This is now working as expected and we can see all sub-folders and files for our bedrock minecraft docker installation.
