### ISSUE TITLE
Which version of bedrock seeds can be used? 

### ISSUE THREAD

**Issue by keepsmilyn** [itzg/docker-minecraft-bedrock-server#168]
We tried to use one of the seeds listed on this website, but it didn't seem to work. Perhaps its due to the "bedrock" version. 

https://www.digminecraft.com/seeds/pocket_edition/biome_extreme_hills.php#version_form

What version of bedrock does this install? Version '1.11' does not appear in the list on this site, but perhaps that is just the version of the code. :-S

**Comment by itzg** [comment]
I don't mess with seeds much, but yes I believe they're version dependent. Right now the latest release from Mojang is 17.10.0.4:

![image](https://user-images.githubusercontent.com/988985/126249950-2f17da9a-818e-4b1f-9593-9be1bf2b1035.png)

You can set `VERSION` to any valid bedrock server version even if it's not explicitly mentioned in the startup script. (Those are there just for convenience.) This is the best place I have found to locate prior version numbers

https://minecraft.fandom.com/wiki/Bedrock_Dedicated_Server#History

So, it looks like `VERSION=1.16.221.01` is what you would want for the seeds on that site.

**Comment by itzg** [comment]
...one more thing to keep in mind with seeds is that it only applies to initial world generation. So you may need to delete away the world data directory between experiments to make sure the seed kicks in as you expect.

**Comment by keepsmilyn** [comment]
Thank you. We are using the latest version as per the 'Environment' variable value being set to 'LATEST'. 

Yes, I realised that changing the seed-level value after restarting the server didn't seem to work. Do we need to delete all installed minecraft files & folders or just a certain folder / directory? (ie: \worlds folder ) .

**Comment by itzg** [comment]
Just removing the worlds folder will be sufficient.

**Comment by keepsmilyn** [comment]
Yes that worked. I deleted the sub-folder within the 'worlds' folder and it created a new one when the minecraft server 'container' was restarted. Thank you. 👍
