### ISSUE TITLE
Failed to extract download URL 'null' when starting container

### ISSUE THREAD

**Issue by unifiedcommsguy** [itzg/docker-minecraft-bedrock-server#181]
Getting the following error when running container. Could be related to [`#31`](https://github.com/itzg/docker-minecraft-bedrock-server/issues/31)

```
Looking up latest version...
Failed to extract download URL 'null' from https://www.minecraft.net/en-us/download/server/bedrock
```
I also get an error when browsing to the URL, "[`AN ERROR HAS OCCURRED`](https://i.imgur.com/CiFBST7.png)"

**Comment by Wiliver** [comment]
+1

**Comment by Wiliver** [comment]
Checking Minecraft's site, I cannot find any download for a bedrock server now

**Comment by DaveDaveDaveDave** [comment]
I had the same issue this evening.  Looks like it was an issue with the Minecraft download site.  It's working now and the LATEST brings in 1.17.11.01 as expected.

**Comment by drewchurch** [comment]
Can also confirm this was not working last night but it is now!

**Comment by unifiedcommsguy** [comment]
I can confirm this is workign again. Sorry for the red herring.
