### ISSUE TITLE
Outdated Server

### ISSUE THREAD

**Issue by MalPaPa** [itzg/docker-minecraft-bedrock-server#184]
I'm pretty new to using Docker, but so far the Itzg repo has been awesome.  

Over the weekend my server image successfully updated to version 1.17.31.01 and my ios and pc versions updated to 1.17.30.  The Minecraft wiki says those should be the most current versions.  But ios and pc players are getting the error: "Could not connect: Outdated Server"  

When I look at the container log it only shows, "[INFO] Running AutoCompaction... | stdout" every six minutes.  

Is anyone else having this issue?

**Comment by itzg** [comment]
The container only looks for newer versions at startup, so restarting the container might get things lined up. If not, please the provide the container logs during that restart.

**Comment by MalPaPa** [comment]
Log after reboot:

DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=1024 from match path            
DEBU[0000] Resolved GID=100 from match path             
+ curlArgs=(-v)
++ id -a
++ ls -ld /data
+ echo 'DEBUG: running as uid=1024 gid=100(users) groups=100(users) with drwxrwxrwx 16 1024 users 4096 Sep 27 19:30 /data'
DEBUG: running as uid=1024 gid=100(users) groups=100(users) with drwxrwxrwx 16 1024 users 4096 Sep 27 19:30 /data
+ downloadPage=https://www.minecraft.net/en-us/download/server/bedrock
+ [[ TRUE != TRUE ]]
+ case ${VERSION^^} in
+ echo 'Looking up latest version...'
Looking up latest version...
+ for a in data-platform
+ for i in {1..3}
++ restify --user-agent=itzg/minecraft-bedrock-server --headers 'accept-language:*' --attribute=data-platform=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock
++ jq -r '.[0].href'
+ DOWNLOAD_URL=https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.31.01.zip
+ [[ -n https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.31.01.zip ]]
+ break 2
+ [[ -z https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.31.01.zip ]]
+ [[ https://minecraft.azureedge.net/bin-linux/bedrock-server-1.17.31.01.zip =~ http.*/.*-(.*)\.zip ]]
+ VERSION=1.17.31.01
+ rm -f restify.err
+ '[' '!' -f bedrock_server-1.17.31.01 ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ allowListUsers=
+ '[' -n '' ']'
+ set-property --file server.properties --bulk /etc/bds-property-definitions.json
+ export LD_LIBRARY_PATH=.
+ LD_LIBRARY_PATH=.
+ echo 'Starting Bedrock server...'
Starting Bedrock server...
+ exec ./bedrock_server-1.17.31.01
NO LOG FILE! - setting up server logging...
[2021-09-27 19:34:25:134 INFO] Starting Server
[2021-09-27 19:34:25:134 INFO] Version 1.17.31.01
[2021-09-27 19:34:25:134 INFO] Session ID ca2490a7-1e49-43e5-b68e-669631f56342
[2021-09-27 19:34:25:135 INFO] Level Name: Bedrock level
[2021-09-27 19:34:25:136 INFO] Game mode: 0 Survival
[2021-09-27 19:34:25:136 INFO] Difficulty: 1 EASY
[INFO] opening worlds/Bedrock level/db
[INFO] IPv4 supported, port: 25801
[INFO] IPv6 not supported
[INFO] Server started.
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 not supported

**Comment by itzg** [comment]
That all looks right and looking at https://www.minecraft.net/en-us/download/server/bedrock, 1.17.31.01 does seem to be the newest server version they provide. The error reported in the client might be beyond the control of the image.

**Comment by MalPaPa** [comment]
Ok thank you.

**Comment by wedgef5** [comment]
I am also having trouble with my server not updating. The log is saying...

WARN Minecraft download page failed, so using existing download of 1.16.220.02

**Comment by itzg** [comment]
@wedgef5 that's quite a common confusion, so no worries at all.
