### ISSUE TITLE
Can't set server properties / don't see worlds folder in mounted volume

### ISSUE THREAD

**Issue by chrisawaters** [itzg/docker-minecraft-bedrock-server#2]
The defaults work. I can connect, but I'm not seeing what I expect when I mount the folder, and my settings file isn't being picked up. 

![image](https://user-images.githubusercontent.com/814045/61674349-78641000-acc1-11e9-9467-bed4abc3a7db.png)

**Comment by itzg** [comment]
Can you provide the `docker run` command you're using (or equivalent)?
