### ISSUE TITLE
Resource_Packs and Behavior_Packs

### ISSUE THREAD

**Issue by StefanRied** [itzg/docker-minecraft-bedrock-server#20]
Hi,

the container with the Bedrock server works great and stable. For a few players and not too large worlds, it even fits into a Google g1-small instance. Which means you can run it a full year with the free Google cloud quota totally at zero cost.
Here comes the problem:

I am trying to add Add-Ons (Resource&Behavior) to a server. Loading them via the clients fails, or I don't get it right.
So I tried loading them directly into the filesystem of the running container and then restarted the container.

docker exec -i -t container_name bash
root@***:/data# ls -l resource_packs/CYBERTRUCK/
total 264
drwxr-xr-x 2 root root   4096 Dec 18 15:18 animations
drwxr-xr-x 2 root root   4096 Dec 18 15:18 entity
-rw-r--r-- 1 root root    484 Nov 26 12:48 manifest.json
drwxr-xr-x 2 root root   4096 Dec 18 15:18 materials
drwxr-xr-x 3 root root   4096 Dec 18 15:18 models
-rw-r--r-- 1 root root 225439 Nov 26 12:48 pack_icon.png
drwxr-xr-x 2 root root   4096 Dec 18 15:18 render_controllers
drwxr-xr-x 3 root root   4096 Dec 18 15:18 sounds
-rw-r--r-- 1 root root    397 Nov 26 13:16 sounds.json
drwxr-xr-x 2 root root   4096 Dec 18 15:18 texts
drwxr-xr-x 4 root root   4096 Dec 18 15:18 textures

root@****:/data# ls -l behavior_packs/CYBERTRUCK/
total 232
drwxr-xr-x 2 root root   4096 Dec 18 15:16 entities
-rw-r--r-- 1 root root    444 Nov 26 12:47 manifest.json
-rw-r--r-- 1 root root 225439 Nov 26 12:48 pack_icon.png

docker stop/start container_name 

NO SUCCESS

If I understand the documentation right, the server is browsing these directories and lists the found resources in the /data/valid_known_packs.json file. However, the manually installed resources and behavior packs are simply not loaded. Also nothing that I found in the log files.

I am not sure if this is actually a bug or if I misunderstood the Bedrock Add-On concept. In case of the latter, please excuse my question here.

Thanks a million for your help.

**Comment by itzg** [comment]
First of all, fantastic feedback and confirmation of g1-small being a viable VM type for this container. I'm doing a similar "experiment" with the Java edition container on a GKE cluster.

As for the issue, I'm afraid I have not yet explored the add-on capabilities of Bedrock edition. Everything you're describing sounds correct to me especially since you're making the changes within the correct `/data` path of the container.

Let's keep this issue open and see if anyone else or further exploration on our parts reveals any answers.

**Comment by igoticecream** [comment]
@StefanRied unzip the .mcpack in /data/resource_packs, then create a json in the world folder: `/data/worlds/{your_world_name_here}/world_resource_packs.json` and put something like this:

```
[
  {
    "pack_id": "9fe06a6d-7cdc-406d-9a3c-7a3e0b67c81a",
    "version": [0, 0, 1]
  },
  {
    "pack_id": "66c6e9a8-3093-462a-9c36-dbb052165822",
    "version": [1, 5, 0]
  }
]
```

The pack_id and the version must match the resource pack's manifest.json

Do the same for behaviors pack if any and thats it

**Comment by StefanRied** [comment]
oh thanks. Yes. this does work now very nicely. I just forgot one bracket above. Also setting the server.proties texturepack-required=true pushes then the addons to the clients, that do not have them yet. By this I can automatically push the addons to my friends connecting to my server. 

@itzg Geoff, we can close this issue now. It was really not an issue, but just a validation that the container runs exactly how it should be.
