### ISSUE TITLE
Unable to start server with example docker-compose.yml

### ISSUE THREAD

**Issue by jasonlearst** [itzg/docker-minecraft-bedrock-server#202]
Hello,

I found that using the example docker-compose.yml I am unable to get the server to start.  I receive the following error:
```
$cat data/restify.err
2021/12/25 19:46:44 Failed to load content: Failed to retrieve response: Get "https://www.minecraft.net/en-us/download/server/bedrock": dial tcp: lookup www.minecraft.net on 127.0.0.11:53: read udp 127.0.0.1:39133->127.0.0.11:53: i/o timeout
```

I was able to resolve this by removing the parameter:
```
sysctls:
      net.ipv4.ip_local_port_range: 39132 39133
```

**Comment by itzg** [comment]
Thank you for reporting this. I didn't intend for those to be included in the final example, so removing was very correct.

**Comment by itzg** [comment]
Example file is now fixed.
