### ISSUE TITLE
Support setting the "server-authoritative-block-breaking" property via environment variables

### ISSUE THREAD

**Issue by Ponyboy47** [itzg/docker-minecraft-bedrock-server#212]
There is a server property named "server-authoritative-block-breaking" which if true, the server will compute block mining operations in sync with the client so it can verify that the client should be able to break blocks when it thinks it can.

It would be nice if there were support for setting this via an environment variable, just like all the other properties. No rush, just noticed this existed today 😄

**Comment by itzg** [comment]
Yes, that'll be easy to add.

**Comment by itzg** [comment]
Latest image now includes this change.
