### ISSUE TITLE
Xbox version cannot see lan games

### ISSUE THREAD

**Issue by txchen** [itzg/docker-minecraft-bedrock-server#219]
I was using this image for a couple months and it worked great.
However recently after I upgraded the client to 1.18 (xbox x game pass version), it can no longer show lan games.

Anybody has the same issue?

**Comment by txchen** [comment]
My android minecraft (latest version) can still see the server.

**Comment by itzg** [comment]
If you're familiar with tcpdump (on Linux) or Wireshark (Mac/Windows) then it might be interesting to watch the port 19132 traffic to see what happens with the multicast ping message that the client sends out.

**Comment by txchen** [comment]
Will try to do that. Before that I just want to quickly confirm if this feature was cut by Microsoft, if someone else also encounter this issue.

**Comment by itzg** [comment]
Not that I know of, but I do know the server discovery part is flaky. I have had times where restarting the iOS client got it to work.

**Comment by txchen** [comment]
Checked again. It worked again. Not sure if the issue was in Xbox OS, Minecraft Xbox version or bedrock server, but seems Microsoft found the bug and fixed it.
