### ISSUE TITLE
/opt/bedrock-entry.sh: line 65: /data/bedrock_server-1.14.1.4: Permission denied

### ISSUE THREAD

**Issue by gingeuk** [itzg/docker-minecraft-bedrock-server#22]
Hello! 

Trying to run the this docker image with the command below and I get the below error constantly regardless of what permissions (even 777) I give the local folder, I've also tried it with 'root' as the owner. I've tried with different versions but this doesn't have any effect.

`docker run -d -e EULA=TRUE -v /home/ginge/docker/minecraft:/data -p 19132:19132/udp itzg/minecraft-bedrock-server`

>time="2019-12-30T08:54:47Z" level=debug msg="Using /data to match uid and gid"
time="2019-12-30T08:54:47Z" level=debug msg="Resolved UID=1000 from match path"
time="2019-12-30T08:54:47Z" level=debug msg="Resolved GID=100 from match path"
time="2019-12-30T08:54:47Z" level=debug msg="stdin is detached, so forwarding is disabled"
Starting Bedrock server...
/opt/bedrock-entry.sh: line 65: /data/bedrock_server-1.14.1.4: Permission denied

The image runs fine if I don't set a volume... 

Any ideas?

**Comment by itzg** [comment]
Judging from that particular line in the script, can you make sure you don’t have any leftover files whose name starts with “bedrock_server”? Remove any of those and try restarting the container again.

**Comment by gingeuk** [comment]
Thanks for the reply, I've tried deleting the files from the folder several
times and started the container again but the same result.

Quite happy to try again when I get back home.

Strange how it will run without a volume, I'll try and check the
permissions with & without the volume but apart from the user I'm confident
they are all the same.

**Comment by gingeuk** [comment]
So tried deleting the files and restarting the container but still get the same result.

Below is a screenshot of the volume directory permissions and the data directory permissions, nothing looks odd to me apart the additional files if the volume is not used.

![image](https://user-images.githubusercontent.com/20688474/71590012-e76e4c00-2b1e-11ea-9149-96595a63b3b9.png)

![image](https://user-images.githubusercontent.com/20688474/71590018-ed642d00-2b1e-11ea-8044-bd6707235aa0.png)

Could be unrelated but if I try to start the server locally on my machine, I still get the permission denied error.

**Comment by itzg** [comment]
I agree, that all seems to look fine even though it's not happy at the end. Can you redo that first view with `ls -aln docker/minecraft/` so I can double check the UID on the files?

**Comment by gingeuk** [comment]
Had a *doh* moment! After further investigation, I noticed the drive that is mounted for my home directory has the "noexec" option. Removed the option and everything is working fine.

**Comment by itzg** [comment]
Aha, that totally makes sense then. I was wondering how the file could be written to the filesystem, but fail on that final execution.

**Comment by henricos** [comment]
Sorry to reopen....

I've been struggling whith a similar message on my OpenMediaVault NAS (Debian)

```
time="2020-04-11T14:58:02-03:00" level=debug msg="Using /data to match uid and gid"
time="2020-04-11T14:58:02-03:00" level=debug msg="Resolved UID=1001 from match path"
time="2020-04-11T14:58:02-03:00" level=debug msg="Resolved GID=100 from match path"
time="2020-04-11T14:58:02-03:00" level=debug msg="stdin is detached, so forwarding is disabled"
Starting Bedrock server...
/opt/bedrock-entry.sh: line 73: /data/bedrock_server-1.14.30.2: Permission denied
```

Here is my compose file:

```
version: "2"
services:
  bds:
    image: itzg/minecraft-bedrock-server:latest
    container_name: minecraft
    network_mode: bridge
    environment:
      - TZ=America/Sao_Paulo
      - EULA=TRUE
      - DIFFICULTY=normal
      - ALLOW_CHEATS=true
    ports:
      - 19132:19132/udp
    volumes:
      - /srv/dev-disk-by-label-DISCO2/minecraft:/data
    restart: unless-stopped
```
Here is the content of the "volume" folder:

![image](https://user-images.githubusercontent.com/7535899/79051251-9681ef80-7c05-11ea-8ceb-c28b21a6d66b.png)

All my other containers uses doker (1001) user and users (100) group

What am I missing??

**Comment by itzg** [comment]
@henricos have you checked that the filesystem for `/srv/dev-disk-by-label-DISCO2/minecraft` does not have the `noexec` option enabled? Use `findmnt /srv/dev-disk-by-label-DISCO2/minecraft` to determine that.
