### ISSUE TITLE
New Server: Is there a way to give players that join initial resources by default?

### ISSUE THREAD

**Issue by rgreen13** [itzg/docker-minecraft-bedrock-server#220]
My son has asked me to setup this server for sometime, but he'd like every player to be given specific resources when they login the first time. Any good way to do that?

**Comment by itzg** [comment]
I suspect you can do that with behavior packs and there might be an existing one for that. If not, this looks like a good description of creating one

https://docs.microsoft.com/en-us/minecraft/creator/documents/behaviorpack

With that said, I haven't tried myself getting those setup server side, but there's been some great instructions provided by others

https://github.com/itzg/docker-minecraft-bedrock-server/issues/156#issuecomment-1005340769

**Comment by rgreen13** [comment]
Thanks!

Solved this by creating a behavior pack using a function as directed by https://wiki.bedrock.dev/commands/loading-commands.html
