### ISSUE TITLE
Minecraft server NOT downloading

### ISSUE THREAD

**Issue by Galactix** [itzg/docker-minecraft-bedrock-server#229]
curl: (7) Failed to connect to minecraft.azureedge.net port 443: No route to host

ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-master.zip

      Double check that the given VERSION is valid

--------
https://minecraft.azureedge.net/bin-linux/

<Error>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:ff6c9124-101e-00b4-5a6d-413ad4000000 Time:2022-03-27T00:01:13.2462687Z
</Message>
</Error>

----------------
https://minecraft.azureedge.net/bin-linux/bedrock-server-master.zip

<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:1a395559-a01e-00e2-1a6d-41d2a4000000 Time:2022-03-27T00:01:46.3625404Z
</Message>
</Error>

**Comment by itzg** [comment]
What did you provide for `VERSION`? "master" is not a valid version. Right now the latest is "1.18.12.01".

**Comment by Galactix** [comment]
Thanks for the quick reply. (I've tried latest, master and previous.)

But I just realized that it is not a problem with your code as I can download the image within Docker terminal.

I've been using Portainer compose, and it keeps giving me the 'Cannot find file' error. It keeps screwing up the request and going to https://minecraft.azureedge.net/bin-linux/
