### ISSUE TITLE
Issue connecting from iMac

### ISSUE THREAD

**Issue by namurdock** [itzg/docker-minecraft-bedrock-server#23]
Hi there, i have the server setup and running on my LAN. I am able to connect my Android device on the wifi. My friend can connect from his house on a PC, so i know my forwarding rules are correct.

Unfortunately the two machines that my kids need to use are some old Mac's. :(

I have tried adding the arguments:

`-Djava.net.preferIPv4Stack=true`

in the JMV arguments, but no joy.

Tried adding the port number to the end of the ip address when connecting, no joy.

Can you let me know if i am barking up the wrong tree? Should i be able to cnnect a Mac java edition to the Bedrock server?

**Comment by itzg** [comment]
Your last question is unfortunately the answer: Java edition clients cannot connect to Bedrock server. As you might have seen, I also provide a [Java edition server](https://hub.docker.com/r/itzg/minecraft-server/) but that won't work then with your Android client.

**Comment by namurdock** [comment]
Thanks @itzg.  Odd that the pc Java edition has no problems connecting though. I'll give the other server a go.

**Comment by itzg** [comment]
Are you totally sure it’s the Java edition on PC? On Windows 10 there are both Java and Bedrock clients available...and they have annoyingly similar launch icons.

**Comment by namurdock** [comment]
It was on windows 8.1 so pretty sure it was Java. Not 100% sure as I didn't see with my own eyes.

Java server worked a treat. So for now the Mac's are happy.

**Comment by itzg** [comment]
Hmm, yeah Windows 8.1 wouldn't have the Bedrock client. In any case, I'm glad to hear the Java edition server works out.
