### ISSUE TITLE
MineCraft Bedrock 1.19 released

### ISSUE THREAD

**Issue by strausmann** [itzg/docker-minecraft-bedrock-server#249]
Good Day,

please upgrade the Docker Image to Bedrock 1.19

Thanks and best regards,

Bjoern

**Comment by itzg** [comment]
The image is not pinned to any particular version. Please refer to `VERSION` and/or restart any running containers to pickup latest version.

**Comment by trizmark** [comment]
After updating to the latest version I am unable to connect to the server. Has anything changed between 1.18 and 1.19 in terms of exposed ports/required network connectivity/etc?

**Comment by matt-dechicio** [comment]
Setting env VERSION to 1.19.1.01 worked for me against Nintendo client 1.19.1. Latest looked like a beta version in the server log.

**Comment by itzg** [comment]
Fired up a new container with

https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/examples/docker-compose.yml

and with my iOS client updated from App Store it connected fine for me.

**Comment by trizmark** [comment]
Yeah, realised that I was on the wrong WiFi network, which had no access to the server. Doh!
Apologies for being dumb! 😬
