### ISSUE TITLE
How to enter the command console？

### ISSUE THREAD

**Issue by moda-haijiao** [itzg/docker-minecraft-bedrock-server#25]
[https://bugs.mojang.com/browse/BDS-1264](url)like this,
`[2020-01-17 06:54:21 INFO] Starting Server`
`[2020-01-17 06:54:21 INFO] Version 1.14.1.4`
`[2020-01-17 06:54:21 INFO] Session ID 70e26961-c28c-4695-9329-ba55d4768f7c`
`[2020-01-17 06:54:21 INFO] Level Name: 主世界`
`[2020-01-17 06:54:21 INFO] Game mode: 0 Survival`
`[2020-01-17 06:54:21 INFO] Difficulty: 3 HARD`
`[2020-01-17 06:54:23 INFO] IPv4 supported, port: 0`
`[2020-01-17 06:54:23 INFO] IPv6 supported, port: 0`
`[2020-01-17 06:54:23 ERROR] Network port occupied, can't start server.`
,I have tried disabling ipv6 but it didn't work still.
Despite all this,the server is still running normally(I Can play on the server normally),so how to enter the command console？(My English is poor,sorry(/ω＼))

**Comment by moda-haijiao** [comment]
`[2020-01-17 06:54:21 INFO] Starting Server
[2020-01-17 06:54:21 INFO] Version 1.14.1.4
[2020-01-17 06:54:21 INFO] Session ID 70e26961-c28c-4695-9329-ba55d4768f7c
[2020-01-17 06:54:21 INFO] Level Name: 主世界
[2020-01-17 06:54:21 INFO] Game mode: 0 Survival
[2020-01-17 06:54:21 INFO] Difficulty: 3 HARD
[2020-01-17 06:54:23 INFO] IPv4 supported, port: 0
[2020-01-17 06:54:23 INFO] IPv6 supported, port: 0
[2020-01-17 06:54:23 ERROR] Network port occupied, can't start server.`

**Comment by itzg** [comment]
Your question is popular :)

Here's one answer
https://github.com/itzg/docker-minecraft-bedrock-server/issues/8#issuecomment-528544941

And some docker compose specifics
https://github.com/itzg/docker-minecraft-bedrock-server/issues/15#issuecomment-552702699
