### ISSUE TITLE
Getting `Failed to extract download URL 'null'` when starting container

### ISSUE THREAD

**Issue by hwittenborn** [itzg/docker-minecraft-bedrock-server#253]
When following the [quickstart](https://github.com/itzg/docker-minecraft-bedrock-server#quickstart) I keep getting this when the container starts:

```
latest: Pulling from itzg/minecraft-bedrock-server
Digest: sha256:950058ddf52c0f962ee60f7b6cf5a3b9080a78b727228fda3c9944362faa2db1
Status: Image is up to date for itzg/minecraft-bedrock-server:latest
DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
Looking up latest version...
Failed to extract download URL 'null' from https://www.minecraft.net/en-us/download/server/bedrock
```

Specifying `-e 'VERSION=LATEST'` doesn't work either, though `PREVIOUS` seems to be working.

**Comment by cjsfj** [comment]
Happening to me as well.

**Comment by hwittenborn** [comment]
> I'm also unable to download the server from that URL

Same here, I've reported an issue on Mojang's issue tracker. Seems to be happening for the Java server for some reason too :P.

**Comment by esarella** [comment]
Looks like the container is unable to download the server from https://www.minecraft.net/en-us/download/server/bedrock. I was able to download it a few days back. I cant download it from the website as well today.

**Comment by itzg** [comment]
Correction: just being able to automate the lookup of the latest version is sufficient. 

As a workaround, the `VERSION` can be set explicitly such as `-e VERSION=1.19.1.01`.

**Comment by hwittenborn** [comment]
> The <a data-platform="serverBedrockLinux"> is now missing the href until a human clicks the accept button.
> 
> Anybody have suggestions for how to automatically identify the URL of the latest download?

I would've sworn there was a tool that could mimic doing stuff with a webpage and running the relevant JavaScript when that happened, I think it might've been PlayWright or something, though I'm not sure off the top of my head.

It doesn't work even after clicking the checkbox though, maybe after that's fixed it'll go back to normal?

**Comment by hwittenborn** [comment]
Versions are working normally on the website now, the Docker image is able to pull in version information fine now too.

Feel free to close it if you think everything's good

**Comment by itzg** [comment]
Cool, thanks for the update.
