### ISSUE TITLE
local users in split screen?

### ISSUE THREAD

**Issue by hypergig** [itzg/docker-minecraft-bedrock-server#262]
Somehow I was able to get split screen to work on my switch and I am trying to understand how this is possible. The steps I used to reproduce this were:

* I stood up a bedrock server in k8s in google cloud
  * added myself and my son to `WHITE_LIST_USERS`
* I applied this [horrible middleman attack](https://apexminecrafthosting.com/how-to-join-a-bedrock-edition-server-on-xbox-switch/#how-to-add-a-minecraft-server-on-nintendo-switch) hack on my switch
* Opened minecraft with my sons switch profile `Logan`
* Logged into **my sons** microsoft account
* logged into the server, all is good, exitted game
* I opened minecraft with switch profile `Dad`
* Logged into **my** microsoft
* Logged into the bedrock server again
* My son with another controller pressed `+` and started a split screen session
* He chose his _switch profile_ `Logan`, this dropped a random `Steve` in the world
  * I got no logs of this user entering the server
* He opened his inventory and had _everything_ that his microsoft user would have

Just for fun, we tried logging into the server from his phone with his microsoft account and it said that he was already logged in.

How is this possible? Did his switch profile somehow keep the association to his microsoft account? If so, why is he a rando `Steve`? The server logs only showed a disconnection for a half baked user with **no** xuid when he left:

```
2022-07-09 20:52:31:038 INFO] Player disconnected: Logan, xuid:
```

`Logan` is the switch profile name, _not_ the microsoft account name. Why didn't I see this user connect? Weird to see a user disconnect without a connection first?

My two biggest concerns are:

1. Is there a way to now somehow backdoor into my server and avoid the white list? (the switch profile named `Logan` is not in the white list) 
2. If this is oddly working, that is great, but because I don't understand how the switch profile and the microsoft account is associated, I am afraid of breaking something and him losing all his inventory.

I was hoping someone here can help me shed some light on this situation? Sorry if this isn't the right place.

**Comment by itzg** [comment]
I would recommend reporting this issue with Mojang. This image just pre-configures and runs the software they provide. Good luck in narrowing that down.

**Comment by hypergig** [comment]
> I would recommend reporting this issue with Mojang. This image just pre-configures and runs the software they provide. Good luck in narrowing that down.

Yep yep, in retrospect I am not sure why i reported this here. Thanks for your reply. Awesome image btw.
