### ISSUE TITLE
How to set custom memory?

### ISSUE THREAD

**Issue by gwimtux** [itzg/docker-minecraft-bedrock-server#265]

**Comment by itzg** [comment]
I don't know of a way to configure that, so therefore the image doesn't expose a way.

**Comment by gwimtux** [comment]
Oh ok. Thank you for trying :heart:

**Comment by double16** [comment]
If I understand you correctly, this is a docker setting that doesn't need any special support from the image. See https://docs.docker.com/config/containers/resource_constraints/

**Comment by gwimtux** [comment]
Thank you also. I'll look into that

**Comment by itzg** [comment]
Ah yes, you're exactly right about the general container memory limit configuration.

**Comment by gwimtux** [comment]
It works! Thank you all :D
