### ISSUE TITLE
Minor issue with ALLOW_LIST_USERS

### ISSUE THREAD

**Issue by stuckj** [itzg/docker-minecraft-bedrock-server#266]
I was trying to update my allow list and wanted to make sure it didn't use the old version so I deleted my `allowlist.json` and set `ALLOW_LIST_USERS` and was confused why it wasn't properly setting the allow list. I figured it out after looking in `bedrock-entry.sh`.

Right here: https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/bedrock-entry.sh#L149

You only create the `allowlist.json` if the file already exists. If you just move that file outside the if block (one line down) it will remove the existing file IF it's there and then create a new one. If there's no existing file it will still create a new one.

I can make a PR if you want, but it's just one line. :)

**Comment by itzg** [comment]
Even one line PRs are great 😀

**Comment by stuckj** [comment]
Done! :)

https://github.com/itzg/docker-minecraft-bedrock-server/pull/267
