### ISSUE TITLE
Change the world that the server loads, and reload the server?

### ISSUE THREAD

**Issue by GAMESTER90** [itzg/docker-minecraft-bedrock-server#27]
Hello, I have been following a long a bit recently while trying to use this project to resurect an old server I had, I have figured out how to us docker runs' -it flag to use the console, and the old ctrl-p + ctrl-q trick to detach without stopping the container, however I would like to boot up an old world I had for my server is it possible at all? when I do run "stop" to stop the server the game the whole container stops, (maybe due to me using the -rm flag as well will try without it and let you guys know)

But otherwise this is an awesome, awesome project will gladly contribute to it what I can if I can.

**Comment by itzg** [comment]
Cool, glad you figured it out. You can also attach an arbitrary directory with `-v` but I sometimes prefer the approach you described. 

Is the issue good to close then?
