### ISSUE TITLE
Restore behavior and resource packs after update

### ISSUE THREAD

**Issue by KUT0K1** [itzg/docker-minecraft-bedrock-server#277]
After an update, the behavior and resource packs have disappeared. Is there a way to restore it automatically?

**Comment by itzg** [comment]
They get backed up to a sub directory that starts with "backup-pre-". You'll need to manually restore the content.

**Comment by KUT0K1** [comment]
Thank you for your reply. True, but I'm looking for an automated solution for custom extensions.

I'm thinking about a mapped volume which, for example, is checked when the server starts and existing extensions are copied into the respective directory on the server.

I would also be open to alternative suggestions. I am happy to make my changes available to everyone.

**Comment by Patchoulino** [comment]
Similar to https://github.com/itzg/docker-minecraft-bedrock-server/issues/194
you can move your behavior_packs, resource_packs and *_packs.json into your words/[your world name]/
I have not had issues with any update moving my mods, this is how my volume looks for reference:
```
$ ls worlds/*/
behavior_packs  level.dat      levelname.txt   valid_known_packs.json
db              level.dat_old  resource_packs  world_behavior_packs.json
```

**Comment by KUT0K1** [comment]
That would be a great solution. I'll try it. Many Thanks

**Comment by itzg** [comment]
From [discussion in Discord](https://discord.com/channels/660567679458869252/660569704288616491/1085044279132569610) it sounds like it’ll work fine to keep the behavior pack directories in place and let the json regenerate.

**Comment by itzg** [comment]
...and re-closing since I now remember the complexity is that the top-level behavior packs includes all the Mojang provided ones too.

**Comment by itzg** [comment]
…however I’m good with re-opening if someone wants to PR a solution to selective restore pack directories after an upgrade.
