### ISSUE TITLE
Preview download url

### ISSUE THREAD

**Issue by sheepa** [itzg/docker-minecraft-bedrock-server#294]
Preview versions are located at `https://minecraft.azureedge.net/bin-linux-preview/bedrock-server-{VERSION}.zip`

So `/bin-linux-preview/` instead of `/bin-linux/`

Would it be possible to accept some env variable for setting this? Or perhaps accepting DOWNLOAD_URL as an env varialble?

Thanks!

**Comment by itzg** [comment]
Yeah, either or both sound like great options. Over on Java edition I have it handle VERSION=SNAPSHOT so could do the same here with a PREVIEW version.

**Comment by Swiftnesses** [comment]
This would be perfect - it appears that with the latest Minecraft Preview on Xbox One, I cannot join the current 'latest' version of the docker. Is there a potential workaround @itzg?

**Comment by itzg** [comment]
Is there a download page for the previews? I just realized that otherwise it will need to be a manual version and a preview flag.

**Comment by Swiftnesses** [comment]
I just downloaded it from here: https://www.minecraft.net/en-us/download/server/bedrock

I replaced the "bedrock_server" on the Docker volume, and restarted it. It's worked for now!

**Comment by itzg** [comment]
Thanks. I hadn't even noticed they added the preview download to that page.
