### ISSUE TITLE
Network port occupied, can't start server

### ISSUE THREAD

**Issue by baukland** [itzg/docker-minecraft-bedrock-server#3]
Hi there

I tryed your bedrock, and it worked just fine. Until i rebooted the debian box. Now i got this everytime i try to start the bedrock server again "Network port occupied...."
You know why this happens? and maby a way to fix this?

Auki

**Comment by itzg** [comment]
Where do you see that error reported? (Trying to narrow down if it’s a container or host conflict)

**Comment by baukland** [comment]
It shows up when i start the container. 
It works fine when you first run it. But if you restart it after a reboot, this happens. If i delete the docker img and remake it. It works. It is only happening after you have stoped it and want to start it again.

Eis

**Comment by itzg** [comment]
Do you see than when invoking `docker start` after rebooting? A different command and/or in a log file?

Speaking of which, if you're not already using the auto restart options this is definitely worth trying out:

https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by baukland** [comment]
Hi again

Been trying autostart also, so its no go :/. So im wondering if, when i use bedrock docker. It happens with other bedrock docks also. If it locks the port in some way. That the docker wont realase the port or something...

**Comment by baukland** [comment]
Seem like if i use uid gid and groups in the makeing of the docker. Then it seems to be starting nicely every time

**Comment by baukland** [comment]
Na, did work for a short time :/

**Comment by baukland** [comment]
Seems like i got it to work now. Hopefully its stabile.
You can close it, it seems ;)
