### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by mainakae** [itzg/docker-minecraft-bedrock-server#30]
Hey!

awesome work with both java and bedrock, great fun and great success. I was wondering if it is in your plans to add arm support (as in java version) for the bedrock edition :)

Best regards,
Pedro

**Comment by itzg** [comment]
Unfortunately we’re limited to the x86 binary provided by Mojang since the Bedrock server is not implemented in Java :( . 

Here’s the download page for info https://www.minecraft.net/en-us/download/server/bedrock/
