### ISSUE TITLE
Cross-platform play

### ISSUE THREAD

**Issue by Fabio-RibeiroB** [itzg/docker-minecraft-bedrock-server#307]
Is there a way to allow console players to join the server?

Bedrock is supposedly cross-platform. My friends have tried downloading apps like BeddrockTogether to join my Bedrock server but only PC players are able to connect. Is there a way around this? Thanks.

**Comment by itzg** [comment]
Yes but from what I understand the consoles and server need to be on the same LAN for normal discovery mechanism. Otherwise look up general solutions for Bedrock server access, since the behavior is no different running as a container.
