### ISSUE TITLE
Failed to process download URL

### ISSUE THREAD

**Issue by emanual4real** [itzg/docker-minecraft-bedrock-server#31]
Getting this error when trying to run image.  Could it be related to b136de9, Upgraded easy-add and used templated URLs?

```
manny@ubuntu:~/docker/minecraft-bedrock$ docker run -p 19132:19132/udp minecraft-bedrock
time="2020-03-02T19:41:36Z" level=debug msg="Using /data to match uid and gid"
time="2020-03-02T19:41:36Z" level=debug msg="Resolved UID=0 from match path"
time="2020-03-02T19:41:36Z" level=debug msg="Resolved GID=0 from match path"
time="2020-03-02T19:41:36Z" level=debug msg="stdin is detached, so forwarding is disabled"
2020/03/02 19:41:37 Unable to find an element with attribute matcher data-platform=serverBedrockLinux
Failed to process download URL
manny@ubuntu:~/docker/minecraft-bedrock$
```

**Comment by itzg** [comment]
No, that's the "fun" of scraping a webpage for data. They seem to have changed the attribute to `data-bi-prtid="serverBedrockLinux"` rather than `data-platform`.

I'll have to update the attribute parameter here
https://github.com/itzg/docker-minecraft-bedrock-server/blob/b136de9b297938a0bb3c0dc8e84a0cabaa8419a0/bedrock-entry.sh#L29

**Comment by itzg** [comment]
Well...I got this change pushed to Docker Hub but realized that some of instances of that page must be getting served from CDNs with the older copy. I'll need to enhance that step to try each of the possible attributes...

**Comment by itzg** [comment]
OK, the latest image will now try either attribute.

**Comment by emanual4real** [comment]
Sweet, I'll have to give it a try soon.  Appreciate your work!

**Comment by vpathuis** [comment]
Looks as if they changed it again. Getting that error again, but now Unable to find an element with attribute matcher data-platform=serverBedrockLinux

**Comment by itzg** [comment]
@vpathuis make sure to re-pull the latest image. There was a new issue and fix that was needed in #155

**Comment by vpathuis** [comment]
Mm, I made a new container (added to docker-compose.yml) and that's where the issue occurs. Nonetheless I deleted it (prune) and started again. Same error. The other containers start fine. Weird.

**Comment by itzg** [comment]
But did you re-pull the image? Such as `docker-compose pull`

**Comment by vpathuis** [comment]
This worked, thnx a lot for the fast reply!

**Comment by iadk47** [comment]
It appears this is an issue again.  

Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
2022/10/31 03:00:45 Unable to find an element with attribute matcher data-platform=serverBedrockLinux

Any assistance would be greatly appreciated.  Thanks!

**Comment by wallmarc** [comment]
Agree that it seems to be a problem again

A workaround that worked for me is to copy the link address from the Linux download button here:
https://www.minecraft.net/en-us/download/server/bedrock


Start the container with an additional environment variable 'DOWNLOAD_URL', e.g.
DOWNLOAD_URL=https://minecraft.azureedge.net/bin-linux/bedrock-server-1.19.41.01.zip
