### ISSUE TITLE
Build on an arm64 Odroid C2

### ISSUE THREAD

**Issue by wahoonie76** [itzg/docker-minecraft-bedrock-server#32]
Hello,

I tried to build the MC-Server image with your dockerfile and it stopps at step 15 with this error:

> Step 15/17 : COPY *.sh /opt/
> COPY failed: no source files were specified

Here is my dockerfile:

> FROM debian
> 
> ARG ARCH=arm64
> 
> RUN apt-get update && \
>   DEBIAN_FRONTEND=noninteractive apt-get install -y \
>     curl \
>     unzip \
>     jq \
>     && apt-get clean
> 
> EXPOSE 19132/udp
> 
> VOLUME ["/data"]
> 
> WORKDIR /data
> 
> ENTRYPOINT ["/usr/local/bin/entrypoint-demoter", "--match", "/data", "--debug", "--stdin-on-term", "stop", "/opt/bedroc$
> ARG EASY_ADD_VERSION=0.5.0
> ADD https://github.com/itzg/easy-add/releases/download/${EASY_ADD_VERSION}/easy-add_${EASY_ADD_VERSION}_linux_${ARCH} /$RUN chmod +x /usr/local/bin/easy-add
> 
> RUN easy-add --var version=0.2.1 --var app=entrypoint-demoter --file entrypoint-demoter --from https://github.com/itzg/$
> RUN easy-add --var version=0.1.1 --var app=set-property --file set-property --from https://github.com/itzg/{{.app}}/rel$
> ARG RESTIFY_VERSION=1.2.0
> RUN easy-add --var version=1.2.0 --var app=restify --file restify --from https://github.com/itzg/{{.app}}/releases/down$
> COPY *.sh /opt/
> 
> COPY property-definitions.json /etc/bds-property-definitions.json
> 
> '#' Available versions listed at
> '#' https://minecraft.gamepedia.com/Bedrock_Edition_1.11.0
> '#' https://minecraft.gamepedia.com/Bedrock_Edition_1.12.0
> '#' https://minecraft.gamepedia.com/Bedrock_Edition_1.13.0
> '#' https://minecraft.gamepedia.com/Bedrock_Edition_1.14.0
> ENV VERSION=LATEST

And my build command:

> sudo docker build -t 'minecraft' .

What did I wrong?

**Comment by itzg** [comment]
That's strange since you do seem to be building it correctly and I double checked that step just now:

```
Step 15/17 : COPY *.sh /opt/
 ---> 9440b77f7abf
Step 16/17 : COPY property-definitions.json /etc/bds-property-definitions.json
 ---> 1d61df9d4da6
```

HOWEVER, the Bedrock server download https://www.minecraft.net/en-us/download/server/bedrock/ only provides a Linux version for amd64, so even if the docker build succeeds the final execution step of the binary would have failed :(

**Comment by itzg** [comment]
...if you want to further debug that `COPY`, just for curiosity sake, add the following before that line in the Dockerfile to see what files did get brought into the build context:

```
COPY . /opt/
RUN ls -l /opt
```
