### ISSUE TITLE
Docker container quitting immediately after starting

### ISSUE THREAD

**Issue by MaestroJAL** [itzg/docker-minecraft-bedrock-server#33]
Hello! First off, thanks for this! My kids have been enjoying this very much. However, recently my container quits. Here are the docker logs:
 
time="2020-03-25T15:27:54Z" level=debug msg="Using /data to match uid and gid"
time="2020-03-25T15:27:55Z" level=debug msg="Resolved UID=1000 from match path"
time="2020-03-25T15:27:55Z" level=debug msg="Resolved GID=1000 from match path"
time="2020-03-25T15:27:55Z" level=debug msg="stdin is detached, so forwarding is disabled"
2020/03/25 15:27:55 Unable to find an element with attribute matcher data-bi-prtid=serverBedrockLinux
Failed to process download URL

Any ideas? I'm not the most docker proficient but I'm learning!

**Comment by MaestroJAL** [comment]
Decided to delete and rebuild it. Problem solved. Thanks!

**Comment by itzg** [comment]
Glad it fixed itself in the end. The "Failed to process download URL" can typically indicate a proxy or networking issue while accessing the Mojang download page.
