### ISSUE TITLE
Offline use?

### ISSUE THREAD

**Issue by jschwalbe** [itzg/docker-minecraft-bedrock-server#335]
I am getting ready to go on a road trip and the kids would love to use their iPads to play minecraft. I've got bedrock running on a pi, but when I try to start it up while offline (as it will be in the car), I get this error:
```
minecraft  | Looking up latest version...
minecraft exited with code 0
```
Which I assume is related to [this issue](https://github.com/itzg/docker-minecraft-bedrock-server/issues/247), though I don't quite understand [the workaround](https://github.com/itzg/docker-minecraft-bedrock-server/discussions/268#discussioncomment-3478556).

**Comment by itzg** [comment]
Actually, it looks like a better workaround/solution is to set `VERSION` to match exactly the version it downloaded while online.

The code should skip over this whole block if it sees the file present and there don't seem to be any other network operations.

https://github.com/itzg/docker-minecraft-bedrock-server/blob/e421ad2ca6a738970e096dc19ec40b39b4dd2388/bedrock-entry.sh#L106

**Comment by jschwalbe** [comment]
I’ll try that later, thanks! For now there seems to be a client side problem(?) where it wants to be logged in before joining any servers (even LAN!), is there something I’m missing?

**Comment by jschwalbe** [comment]
“You need to authenticate to Microsoft Services”

**Comment by jschwalbe** [comment]
Not seeing anything in the server logs when I try. It’s almost like the client app doesn’t even try connecting. (Unless there are more logs for me to see besides the console.)

**Comment by itzg** [comment]
Oh, I misunderstood and thought that was a message you saw in server logs. Unfortunately I'm out of ideas then.

**Comment by jschwalbe** [comment]
apparently `ONLINE_MDOE` is not the right way to spell `ONLINE_MODE`!! Haha
Spell check and now it's working as expected. Had to set WHITE_LIST to false as well. Seems like it doesn't remember where people were for spawning purposes, unfortunately.
