### ISSUE TITLE
New release plans?

### ISSUE THREAD

**Issue by aviatorb** [itzg/docker-minecraft-bedrock-server#342]
Do you plan to create a new release?  I use TrueCharts (https://truecharts.org/charts/stable/minecraft-bedrock/), and they pull an image from the latest numbered release at docker hub.  Since that version, 2022.1.0, matches the latest release in this repo, I assume that generating a new release here triggers generating the image in docker hub. The TrueCharts developers would then have a new image to which they could update (after some work on their part).

A new release would enable us to benefit from the numerous bug fixes, new config settings, and other enhancements that you have worked so hard to make.

**Comment by itzg** [comment]
I'm sorry about that. I'll get a release kicked off and make sure to include those with a reminder I created for myself on the Java image repo.

**Comment by itzg** [comment]
Wow, huge release 😀

https://github.com/itzg/docker-minecraft-bedrock-server/releases/tag/2023.7.1

**Comment by aviatorb** [comment]
That was fast!  Thanks for all the great work you are doing here.
