### ISSUE TITLE
Error downloading minecraft server zip, curl fails

### ISSUE THREAD

**Issue by peterswolf** [itzg/docker-minecraft-bedrock-server#358]
Hi,

I'm getting this issue in the logs when running the docker: "curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)". What am I doing wrong?

Here's the full debug output:

+ case ${VERSION^^} in
+ echo 'Looking up latest version...'
+ lookupVersion serverBedrockLinux
+ platform=serverBedrockLinux
+ for i in {1..3}
++ jq -r '.[0].href'
++ restify --user-agent=itzg/minecraft-bedrock-server --headers 'accept-language:*' --attribute=data-platform=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock
+ DOWNLOAD_URL=https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip
+ [[ -n https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip ]]

2
+ [[ -z https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip ]]
+ [[ https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip =~ http.*/.*-(.*)\.zip ]]
+ VERSION=1.20.32.03
+ rm -f restify.err
+ '[' '!' -f bedrock_server-1.20.32.03 ']'
+ [[ ! -n https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip ]]
+ [[ /tmp != /tmp ]]
++ basename https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip
+ TMP_ZIP=/tmp/bedrock-server-1.20.32.03.zip
+ echo 'Downloading Bedrock server version 1.20.32.03 ...'
Downloading Bedrock server version 1.20.32.03 ...
+ curl -v -o /tmp/bedrock-server-1.20.32.03.zip -fsSL https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip
*   Trying 23.59.177.69:443...
* Connected to minecraft.azureedge.net (23.59.177.69) port 443 (#0)
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [29 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4735 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=*.azureedge.net
*  start date: May 17 23:32:14 2023 GMT
*  expire date: May 11 23:32:14 2024 GMT
*  subjectAltName: host "minecraft.azureedge.net" matched cert's "*.azureedge.net"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure TLS Issuing CA 05
*  SSL certificate verify ok.
} [5 bytes data]
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /bin-linux/bedrock-server-1.20.32.03.zip]
* h2h3 [:scheme: https]
* h2h3 [:authority: minecraft.azureedge.net]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x55fd02df0c70)
} [5 bytes data]
> GET /bin-linux/bedrock-server-1.20.32.03.zip HTTP/2
> Host: minecraft.azureedge.net
> user-agent: curl/7.88.1
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/2 200 
< content-length: 91031974
< content-type: application/octet-stream
< content-md5: Mz50y2KtwAl9AaFMmac86A==
< last-modified: Thu, 05 Oct 2023 16:04:34 GMT
< accept-ranges: bytes
< etag: "0x8DBC5BCC4AB5F0C"
< server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: dec36d49-d01e-002a-5ea8-f74393000000
< x-ms-version: 2014-02-14
< x-ms-lease-status: unlocked
< x-ms-lease-state: available
< x-ms-blob-type: BlockBlob
< date: Wed, 11 Oct 2023 18:58:55 GMT
< 
{ [5 bytes data]
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Connection #0 to host minecraft.azureedge.net left intact
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
+ echo 'ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip'
+ echo '      Double check that the given VERSION is valid'
ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.32.03.zip
+ exit 2
      Double check that the given VERSION is valid

**Comment by itzg** [comment]
Unfortunately this is something unique to your network; however, the most common cause I have heard for odd network connectivity issues is a mismatch in [MTU](https://www.baeldung.com/cs/tcp-max-packet-size) of the docker network vs your LAN network.

**Comment by peterswolf** [comment]
Thanks for the quick response itzg, I just checked MTU and seems to be level across the layers at 1500. I'll poke around and some of my other settings.

**Comment by xxorde** [comment]
Same problem here. I would not say my setup is "clean" but all other pods seem to work fine.

**Comment by xxorde** [comment]
https://github.com/itzg/docker-minecraft-bedrock-server/discussions/361

**Comment by xxorde** [comment]
This is still affecting me, and it is getting more problematic. You can't use an older version of the docker image, for it is no longer supported by the current client.

**Comment by itzg** [comment]
Try switching to https://docker-minecraft-server.readthedocs.io/en/latest/misc/examples/#bedrock-compatible-server
