### ISSUE TITLE
Version 1.14.60.5

### ISSUE THREAD

**Issue by claflico** [itzg/docker-minecraft-bedrock-server#36]
Looks like there was a hotfix yesterday and now android clients are getting a warning that the server version is outdated. 

The version it shows in the client is 1.14.60.5 so can you provide an update for a pinned ENV version? 

I changed the VERSION to LATEST for now but prefer to use pinned versions whenever possible.

Thanks.

**Comment by itzg** [comment]
This is now pushed to Docker Hub.
