### ISSUE TITLE
Unable to connect via iOS unless tcp 19132 is also open

### ISSUE THREAD

**Issue by josephdpurcell** [itzg/docker-minecraft-bedrock-server#364]
I'm running this command on an Ubuntu machine:

```
docker run -it -e EULA=TRUE -p 19132:19132/udp itzg/minecraft-bedrock-server
```

But, I had two problems: first my iPad wouldn't connect at all it would not get a ping and would not connect. Second, after enabling TCP port it would hang on building world.

To solve these I modified the command from the readme to be this:

```
docker run -it -e EULA=TRUE -p 19132:19132/udp -p 19132:19132 --memory=1024g --cpus=2 itzg/minecraft-bedrock-server
```

I'm curious if anyone else ran into something similar or if I'm experiencing user error?

PS. Awesome repo! I'm excited to play this with my kiddo who is obsessed with Minecraft right now. My next step now that the quickstart is working is to move this to a docker compose and learn about world configuration.

**Comment by itzg** [comment]
I think I have intermittently heard similar reports over the years. It's still a mystery to me why it would make a difference...but if it gets your setup working then go for it! 😀

**Comment by josephdpurcell** [comment]
The hypothesis I had with it was maybe the application is doing a ping test to see if the port is open over TCP, but that is a wild guess, and may be unsubstantiated.

The one-liner docker run I posted was working, then it stopped working, but only on 1 of my 2 iPads. The one it was working on was a much older model, the newer one would fail to connect.

I disabled IPv6 on the server host machine and that may have fixed it? Which, makes me wonder if my original issue when I added TCP 19132 was it was trying to connect over IPv6 and failing. I see that IPv6 is supposedly supported.

All that to say, I haven't been rigorous enough in my testing to know for certain what my issue is.

**Comment by itzg** [comment]
In general, their network discovery mechanism seems to be very flaky. Like you I have had mixed results all on the same network and sometimes the same device.

**Comment by josephdpurcell** [comment]
I enabled UDP only on my firewall and was still able to connect.

Based on what others are saying as well as my own empirical evidence I created this ticket in error.

The documentation is correct, you only need UDP. I even see ping time on the Servers tab.
