### ISSUE TITLE
docker run error downloading the server binary

### ISSUE THREAD

**Issue by lfischer** [itzg/docker-minecraft-bedrock-server#366]
latest version fails to start with this error:

```Downloading Bedrock server version 1.20.40.01 ...
curl: (6) getaddrinfo() thread failed to start
ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.40.01.zip
      Double check that the given VERSION is valid```

**Comment by the-redone** [comment]
> latest version fails to start with this error:
> 
> ```
> curl: (6) getaddrinfo() thread failed to start
> ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.40.01.zip
>       Double check that the given VERSION is valid```
> ```

Same, thought my container was broken or the server data, new container, different name, no data, same issue

**Comment by lfischer** [comment]
the issue happened on an old Ubuntu 18 LTS which is not supported anymore.
