### ISSUE TITLE
Cannot change "Multiplayer Game" setting

### ISSUE THREAD

**Issue by jacobcrawford** [itzg/docker-minecraft-bedrock-server#381]
When "Multiplayer Game" setting is on, it is not possible to do ps4 split screen, so it would be much appreciated if this could be turned off somehow. I m not sure how this is reflected in the properties file.

![image](https://github.com/itzg/docker-minecraft-bedrock-server/assets/22328547/383f9400-da5b-48bf-86b0-072102c2fdab)

**Comment by itzg** [comment]
I think you'll need to search the internet for your issue since I'm not sure how that relates to the image startup automation.

**Comment by jacobcrawford** [comment]
I did a few hours of research yesterday and it seems that it is not a part of any Minecraft bedrock server configuration i could find, so i thought it might be a part of building the minecraft binary?

**Comment by itzg** [comment]
I don't build the binary, it is downloaded from Mojang at https://www.minecraft.net/en-us/download/server/bedrock

**Comment by jacobcrawford** [comment]
Yeah sorry it relates to the problem that you have to buy PS Plus to play split-screen on a local setup :(
I just found out that this is an old and known issue that the Mojang team does not really prioritize: https://bugs.mojang.com/browse/BDS-1634
Sorry for wasting your time good sir!

**Comment by itzg** [comment]
I'm glad you figured out the root cause...💰 💰 💰
