### ISSUE TITLE
Ask for an Configuration Tutorial

### ISSUE THREAD

**Issue by ridwankustanto** [itzg/docker-minecraft-bedrock-server#4]
Hey, glad to found this docker image to make dedicated server and I'm interesting to try this out. But, is there any step-by-step for server configuration for generating the world?

Thanks!

**Comment by itzg** [comment]
Good question. I really need to enhance this image to be more configurable like my Java edition image. After that change things would be stable enough to provide a tutorial.

In the meantime, a `server.properties` can be pre-created in the volume attached to `/data` that contains the config documented here

https://minecraft.gamepedia.com/Server.properties#Bedrock_Edition_3

**Comment by nelsonblaha** [comment]
Possibly related: I get a bunch of permission denied errors to create a bunch of structures, as well as server.properties. I've tried it with and without a pre-existing `server.properties`. I've also verified that the docker user has rwx access to the bound volume paths and even chown'd them for the docker user but no dice. Any ideas? I'll help write documentation

**Comment by itzg** [comment]
@nelsonblaha sounds like yours might be a different scenario, but would be glad to take you up on the documentation offer once I get the properties configuration mechanism in place.

It'll be good to create a separate issue for the permission denied errors. In that issue description can you describe how you're starting the container (like `docker run` command line) and what the initial logs show? For comparison, a fresh container without `/data` mounted to an external volume gives me:

```
time="2019-08-17T06:50:13Z" level=debug msg="Using /data to match uid and gid"
time="2019-08-17T06:50:13Z" level=debug msg="Resolved UID=0 from match path"
time="2019-08-17T06:50:13Z" level=debug msg="Resolved GID=0 from match path"
time="2019-08-17T06:50:13Z" level=debug msg="failed to read stdin" error=EOF
Downloading Bedrock server 1.12.0.28 ...
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2019-08-17 06:50:19 INFO] Starting Server
[2019-08-17 06:50:19 INFO] Version 1.12.0.28
[2019-08-17 06:50:19 INFO] Session ID e5cab791-67e6-4b29-9474-cf58edb5e603  
[2019-08-17 06:50:19 INFO] Level Name: Bedrock level
[2019-08-17 06:50:19 INFO] Game mode: 0 Survival
[2019-08-17 06:50:19 INFO] Difficulty: 1 EASY
[2019-08-17 06:50:21 INFO] IPv4 supported, port: 19132
[2019-08-17 06:50:21 INFO] IPv6 not supported
[2019-08-17 06:50:21 INFO] IPv4 supported, port: 58085
[2019-08-17 06:50:21 INFO] IPv6 not supported
[2019-08-17 06:50:23 INFO] Server started.
```

**Comment by nelsonblaha** [comment]
Looks like I just needed a fresh start. I had some junk in Portainer from a different repo's attempt at this. Sorry to muck up this issue.

**Comment by itzg** [comment]
@ridwankustanto I have now enhanced the image with the ability to configure all of the server properties via environment variables. They are listed in this new section along with an example of a `docker run` usage:

https://github.com/itzg/docker-minecraft-bedrock-server#server-properties

Let me know what type of information or tutorial would help to further make use of the new options.

**Comment by itzg** [comment]
...I have also added an example of deploying with Kubernetes

https://github.com/itzg/docker-minecraft-bedrock-server#deploying-with-kubernetes

Stay tuned for a Medium article where I'll describe how I deployed this to Google Cloud.

**Comment by ridwankustanto** [comment]
> @ridwankustanto I have now enhanced the image with the ability to configure all of the server properties via environment variables. They are listed in this new section along with an example of a `docker run` usage:
> 
> https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
> 
> Let me know what type of information or tutorial would help to further make use of the new options.

Thank you! I appreciate it.

**Comment by bingobob** [comment]
thanks, the enviroment variables work for me, but where does that leave server.properties file, do I/ can I/ should I edit that also?

**Comment by itzg** [comment]
@bingobob , with the environment variable to property mapping support, it shouldn't be necessary to manually edit the server.properties. The mappings will only touch the property lines that correspond to set environment variables, so it can coexist with manual modifications.

FYI, if there's any property missing from the mapping, I (or a PR) can easily extend the mapping definitions in

https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/property-definitions.json
