### ISSUE TITLE
Could not connect: Outdated client!

### ISSUE THREAD

**Issue by bingobob** [itzg/docker-minecraft-bedrock-server#400]
Hi,

Thanks for this software brilliant fun for my son and his pal.

Was working fine and i can connect from my android phone. On my son's android tablet though, he's now getting "Could not connect: Outdated client!", worked initially.

Any ideas - pretty sure client and server are up to date?

Thanks

**Comment by itzg** [comment]
> Any ideas - pretty sure client and server are up to date?

But it says it's not 😀 Sometimes there is lag in the Play (and Apple) store as app updates go through approval process. Keep checking for updates there.

**Comment by bingobob** [comment]
Thanks for replying so fast... and yes - never in doubt ;-)

Updating the client and the problem is gone!

Sorry to bother.

Thanks
