### ISSUE TITLE
Adjust the `docker-compose` command to `docker compose` in the README file

### ISSUE THREAD

**Issue by ThiagoSolfo** [itzg/docker-minecraft-bedrock-server#403]
The command `docker-compose` command is wrong, the correct one is `docker compose`. Without the `-`

![image](https://github.com/itzg/docker-minecraft-bedrock-server/assets/61445366/8aead10a-af05-498d-89d6-19edb8b0ff69)
https://docs.docker.com/reference/cli/docker/compose/

**Comment by itzg** [comment]
Thank you for pointing out the needed docs update. Just to clarify `docker-compose` is not **wrong**, it's now just a wrapper script/command that calls `docker compose` for backward compatibility. 

When some of these docs were written, the `compose` subcommand didn't exist and `docker-compose` was a completely separate tool (written in Python). 

PRs are welcome BTW.
