### ISSUE TITLE
Port for Armv7/RPi

### ISSUE THREAD

**Issue by yllekz** [itzg/docker-minecraft-bedrock-server#41]
Is there any build for the Raspberry Pi/ARMv7 like there is for the Java Edition? I'd like to run this off of my RPi4b if possible but the regular build fails with standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by itzg** [comment]
Unfortunately Mojang only provides an x86 binary:

https://www.minecraft.net/en-us/download/server/bedrock/
