### ISSUE TITLE
Investigate issues with mv command during version backup

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-bedrock-server#413]
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1236041916278378567)

> I'm using the Minecraft BDS image with Docker. When I restart my container, if the BDS version has updated, I get a couple `mv` errors about some backup directory not being empty, and then the whole thing fails, causing the container to exit. If I just start it up again right away, everything is fine. Any ideas? The 2 errors are the same every time:
`mv: cannot move 'resource_packs/chemistry to 'backup-pre-1.20.81.01/chemistry': Directory not empty`
`mv: cannot move  'resource_packs/vanilla to 'backup-pre-1.20.81.01/vanilla': Directory not empty`
I don't know what it means by the directory not being empty, I haven't edited this part of the image that I'm aware of.

**Comment by lingfengchencn** [comment]
same issues .. can we backup to  differenet folder  backup-pre- BP / BP?

**Comment by othorp** [comment]
Issue caused by https://github.com/itzg/docker-minecraft-bedrock-server/pull/362
