### ISSUE TITLE
Looks like the release of 2024.1.0 is failing

### ISSUE THREAD

**Issue by kgtkr** [itzg/docker-minecraft-bedrock-server#416]
It seems that [2024.1.0](https://github.com/itzg/docker-minecraft-bedrock-server/releases/tag/2024.1.0) [fails to build](https://github.com/itzg/docker-minecraft-bedrock-server/actions/runs/7434157139/job/20228144990) and cannot be uploaded to docker hub
https://hub.docker.com/r/itzg/minecraft-bedrock-server/tags

I would appreciate it if you could provide me with the latest release of the fixed version.

**Comment by itzg** [comment]
The `latest` image tag is always the latest, but if you were needing a pinned version then there is now `2024.5.0`

**Comment by kgtkr** [comment]
thank you. I was able to use the pinned version.
