### ISSUE TITLE
Sending a command without attaching the container

### ISSUE THREAD

**Issue by gfaugere** [itzg/docker-minecraft-bedrock-server#42]
Hello,

I've successfully attached the container and sent commands this way - but I want to write a script that would send a message `say "The server will be going down in 5 minutes!"` before stopping the container, backing off the data, and restarting it.
Any way to do that (the "send the command from a script" part)?

Thanks!

**Comment by itzg** [comment]
The challenge I see with scripting a docker attach is emulating the control sequence to detach. But maybe just sending the equivalent control codes somehow would work. The detach sequence is actually a command line argument to the attach, so maybe something more scripting friendly could be specified.
