### ISSUE TITLE
Issues with certain blocks not being available for collections

### ISSUE THREAD

**Issue by PatMitchell-Tech** [itzg/docker-minecraft-bedrock-server#429]
I am having certain problems with my docker bedrock 1.21 server on my lan. Some of my clients will mine in certain patches and not have the ability to grab the items they mined even if they hover over like you would to normally grab things. I have also found that it seems to be a certain radius of blocks that can’t be picked up but once you travel a little bit you can mine. I noticed this is in patches and in most spots you can grab what you mine. I have also found that mobs in the glitched radius cannot move or attack you and seem as though they are stuck by invisible blocks. I have reviewed the docker logs by issuing docker log <container id> yet there isn’t any apparent issues. I just wanted to bring this up as it a glitch in looking to find a soloution for. It has happened with gravel and iron so far. If there is any information and or solutions that could be provided towards this issue that would be greatly appreciated.

**Comment by itzg** [comment]
This doesn't sounds like a problem specific to this docker image. I would suggest looking in the Mojang bug tracker.

**Comment by PatMitchell-Tech** [comment]
Thank you for the quick response. I’m going to close this issue and do some more research on if this is a current ongoing issue with 1.21 bedrock. I’m going to see if I can find a solution that route.
