### ISSUE TITLE
Could not connect: Outdated client!

### ISSUE THREAD

**Issue by tomjuggler** [itzg/docker-minecraft-bedrock-server#435]
`docker run -d -it -e EULA=TRUE -e VERSION=LATEST -p 19132:19132/udp -v mc-bedrock-data:/data itzg/minecraft-bedrock-server`

Am I doing something wrong here? It should get the latest version, right? Trying to connect from Android but all it says is "Could not connect: Outdated client!" Version displayed on visible LAN Game is Bedrock level v1.21.2

**Comment by itzg** [comment]
The "client" in "outdated client" would refer to your Android device I believe. You can set the server to run a version that matches -- or check for updates in the Play store.

**Comment by tomjuggler** [comment]
> The "client" in "outdated client" would refer to your Android device I believe. You can set the server to run a version that matches -- or check for updates in the Play store.

My 10 year old son is laughing and says I'm a total Noob for missing that - thanks it works now after Android app update!

**Comment by tomjuggler** [comment]
Fixed with Android app update

**Comment by itzg** [comment]
Glad to hear it was the easy fix 😀
