### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by ohmantics** [itzg/docker-minecraft-bedrock-server#438]
With a brand new Ubuntu 24.0.4 VM, using a wide variety of the compose examples seen here, I'm not able to see the server (1.21.3.01) from an iPad client (1.21.2). With netstat, I see that the 19132 UDP port is open on the docker host. I see no traffic go by on that port from packet captures in my router, which is setup to pass all traffic and that otherwise works fine. I was able to connect to the outside world from a shell in the container and update packages with apt, etc. so container networking is otherwise working.

What traffic should I be seeing? How can I test if the server is working? (Can I poke some packets at it to prompt a response?)

From past issues, this seems like a common-enough symptom that some searchable concrete debug steps would probably help folks.

**Comment by itzg** [comment]
Yes it's a common problem but is beyond the control of this image. It is Mojang's problem in the bedrock dedicated server software. As such I'm not sure why I should have to provide debug steps for their problem. 

In short though, yes you should be looking for UDP packets on port 19132. What do you mean by "see" though? If you mean LAN discovery then there are broadcast packets to look for. There's a special IP address for that -- you'll have to research that.

**Comment by ohmantics** [comment]
I mean I don't see UDP 19132 packets in tcpdump on the docket host.

**Comment by itzg** [comment]
Sorry, what I meant to ask is if in the iPad client are you looking in the friends tab or have manually added the server with its IP address in the servers tab?

**Comment by ohmantics** [comment]
Both. It doesn't appear in Friends and when manually added it presents a red dot for Ping and doesn't connect.

**Comment by itzg** [comment]
Sounds like a definite Mojang problem then.

**Comment by ohmantics** [comment]
So I should try forcing an older server release?

**Comment by itzg** [comment]
No...I'm saying if you're not seeing the client attempt to connect then it's a client issue. The client is the one that starts sending packets to the server, not the other way around.

One last piece of advice: as mentioned in the existing issues, try force quitting the iPad app. Sometimes that has fixed connectivity issues for me.

**Comment by ohmantics** [comment]
You're right -- it is a client issue. The ding dongs at Microsoft don't show LAN games if the Microsoft account of the Minecraft player is a minor.
