### ISSUE TITLE
How to enable experiments?

### ISSUE THREAD

**Issue by josephdpurcell** [itzg/docker-minecraft-bedrock-server#441]
I want to install https://github.com/SIsilicon/WorldEdit-BE but it says "Beta APIs" must be enabled. In Minecraft, even if I'm an operator, I cannot toggle the "Beta APIs" option. It is greyed out.

I see https://old.reddit.com/r/Minecraft/comments/11l5c4k/multi_server_with_120_additions/jbbxao3/ discusses editing the `level.dat` file which by default is at `worlds/Bedrock level/level.dat`. I have not had success in editing that type of file on Ubuntu nor Mac.

How does one enable experiments?

**Comment by josephdpurcell** [comment]
Ah, I finally found my old comment over here https://github.com/itzg/docker-minecraft-bedrock-server/discussions/373#discussioncomment-7874376.

I see https://www.reddit.com/r/MinecraftCommands/comments/hg9u2x/does_anyone_know_of_any_116_nbt_editors_for_macs/ which says Minecraft v1.16 files don't work with webNBT. Perhaps there is a new wave of NBT editing related issues that I can't find posts about?

**Comment by itzg** [comment]
Can this issue be closed then? Or I can convert it to a discussion since it's not really an issue that's specific to this image.

**Comment by josephdpurcell** [comment]
Closing in favor of https://github.com/itzg/docker-minecraft-bedrock-server/discussions/373
