### ISSUE TITLE
crash after some minutes on orange pi 5 (arm64)

### ISSUE THREAD

**Issue by ramide1** [itzg/docker-minecraft-bedrock-server#444]
Running AutoCompaction...
libc++abi: terminating due to uncaught exception of type std::__1::system_error: Operation not permitted

Package: com.mojang.minecraft.dedicatedserver
Version: 1.21.3.01
OS: Linux
Server start: 2024-08-03 14:21:09 -03
Dmp timestamp: 2024-08-03 14:28:34 -03
Upload Date: 2024-08-03 14:28:34 -03
Session ID: 71a87de5-4f5e-4649-b289-b07acc7119d4
Commit hash: 60bf22dee81e74537e6397c11c0fbce219ca99d2
Build id: 26164172
CrashReporter Key: 8c4937c1-64cb-3532-a8dc-1deb28f67293

**Comment by itzg** [comment]
Please contact Mojang for support.
