### ISSUE TITLE
Unstable Behavior and Connection Issues 

### ISSUE THREAD

**Issue by PedroViniciusMelo** [itzg/docker-minecraft-bedrock-server#446]
I'm running the container on a Raspberry Pi within a LAN setup, but I've been encountering several unusual issues:

1. Inability to place or break blocks in the game.
2. The server unexpectedly shuts down.
3. When trying to rejoin the world, the game gets stuck on the "Building Terrain" screen.
4. The SSH connection used by the minecraft-bedrock-backup container randomly disconnects.

I'm looking for guidance on how to diagnose and resolve these problems. Any tips or troubleshooting steps would be greatly appreciated!
Here is the log a got when a crash happend:

2024-08-22 23:52:24:286 INFO] Package: com.mojang.minecraft.dedicatedserver
Version: 1.21.20.03
OS: Linux
Server start: 2024-08-22 23:43:24 UTC
Dmp timestamp: 2024-08-22 23:52:24 UTC
Upload Date: 2024-08-22 23:52:24 UTC
Session ID: c8c98f76-e0cb-4935-ae5c-b903f005e99d
Commit hash: 71ab5eb9d016c4ec310b413fbe291f3cfea6e545
Build id: 26660154
CrashReporter Key: 8c4937c1-64cb-3532-a8dc-1deb28f67293

Crash
[2024-08-22 23:52:24:286 INFO] 
2024-08-22T23:52:24.522Z	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}
2024-08-22T23:52:24.522Z	INFO	mc-server-runner	Done

**Comment by itzg** [comment]
If you're getting a crash report, then I would suggest reporting that to Mojang.
