### ISSUE TITLE
Add health check

### ISSUE THREAD

**Issue by double16** [itzg/docker-minecraft-bedrock-server#46]
Please add a health check. A basic TCP port check using netcat `nc` would be good. Even better would be a admin command to verify status.

**Comment by itzg** [comment]
One got added recently in https://github.com/itzg/docker-minecraft-bedrock-server/pull/39 . Can you double check you have the latest image and see if the health check now works for you?

**Comment by double16** [comment]
Yep, it's there. I updated 12 days ago, nice to see you're improving often. Thanks!
