### ISSUE TITLE
Download URL

### ISSUE THREAD

**Issue by sheepa** [itzg/docker-minecraft-bedrock-server#460]
The download URL for the server zip have changed from `https://minecraft.azureedge.net/bin-linux/bedrock-server-{VERSION}.zip` to `https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-{VERSION}.zip`

This all works fine when specifying `LATEST` or `PREVIEW` as the VERSION as it will lookup the correct URL. However when setting a specific version the URL is hardcoded to the old one.

Would it not make sense it let it use the same lookup code or perhaps even allowing setting an environment variable DOWNLOAD_URL that will take precedence if set to allow workarounds for potential future changes?

**EDIT:** It seems like the old link is now(?) working for all(?) versions except 1.21.31.04.

Thanks!

**Comment by itzg** [comment]
> **EDIT:** It seems like the old link is now(?) working for all(?) versions except 1.21.31.04.

In that case, I'd prefer to leave it as is since that version will quickly become lost to the sands of time.

Can this issue be closed then?

**Comment by ThiagoSolfo** [comment]
The container doesn't start anymore, how to fix this?
![WindowsTerminal_xvOvcJmn8m](https://github.com/user-attachments/assets/59de04c6-b0eb-4cbc-a270-e6a84a36ada9)

**Comment by itzg** [comment]
@ThiagoSolfo you posted on the wrong issue. Yours is a duplicate of #458 and has already been fixed. Re-pull the image.

**Comment by ThiagoSolfo** [comment]
@itzg thanks, it worked

**Comment by thedhruvn** [comment]
@itzg I made a fix for this, but maybe we don't need it anymore? Do you want me to submit a PR on this?

**Comment by Doobla** [comment]
This issue is recurring.  I can download https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.124.2.zip but minecraft.azureedge.net doesn't even resolve.  Therefore, I end up with a container that won't start...

```
ERROR failed to download from https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.124.2.zip
curl: (6) Could not resolve host: [minecraft.azureedge.net](http://minecraft.azureedge.net/)
      Double check that the given VERSION is valid
```

ios clients have all updated to 1.21.124 and I'm just trying to get the server to a version they can join, but no variation of 1.21.124 seems to be allowed by the container.

**Comment by linkworkreal-lgtm** [comment]
This issue has already been fixed and the[ version ](https://minecrftapkmod.com.mx/)is updated on the server
