### ISSUE TITLE
behaviour packs deleted after stop and start container

### ISSUE THREAD

**Issue by fingerbier** [itzg/docker-minecraft-bedrock-server#471]
when i place behaviour packs in the folder _data/behavior_packs and stop and start the container again, all custom packs are deleted instantly. thats not the case when restarting the container, nor doeas it happen with the data in _data/ressource_packs.

**Comment by itzg** [comment]
Please provide the container startup logs for when that happens.

**Comment by fingerbier** [comment]
i'm sorry. don't know what was happening yesterday. When testarting this morning, trying to see something in the logs, everything works fine. 
so there i no issue, perhaps i have done something wrong the last time
