### ISSUE TITLE
Server does not start after docker restart

### ISSUE THREAD

**Issue by Wessi99** [itzg/docker-minecraft-bedrock-server#472]
I wanted to do an update and restarted the Docker Container. However, the server won't boot anymore. I've already completely deleted the container and set it up again, but the same problem remains.

DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
Looking up latest version...
DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
Looking up latest version...
DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
Looking up latest version...

Translate by google translate

**Comment by itzg** [comment]
I'm not sure what is happening without any kind of exit code or details. Please set the environment variable `DEBUG` to "true" and provide those logs.

**Comment by Wessi99** [comment]
DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
+ curlArgs=(-v)
++ id -a
++ ls -ld /data
+ echo 'DEBUG: running as uid=0(root) gid=0(root) groups=0(root) with drwxrwxrwx 14 root root 4096 Nov 10 11:19 /data'
DEBUG: running as uid=0(root) gid=0(root) groups=0(root) with drwxrwxrwx 14 root root 4096 Nov 10 11:19 /data
++ pwd
+ echo '       current directory is /data'
       current directory is /data
+ export HOME=/data
+ HOME=/data
+ downloadPage=https://www.minecraft.net/en-us/download/server/bedrock
+ [[ TRUE != TRUE ]]
+ case ${VERSION^^} in
+ echo 'Looking up latest version...'
Looking up latest version...
+ lookupVersion serverBedrockLinux
+ platform=serverBedrockLinux
+ customVersion=
+ for i in {1..3}
++ restify --user-agent=itzg/minecraft-bedrock-server --headers 'accept-language:*' --attribute=data-platform=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock
++ jq -r '.[0].href'
++ echo ''
+ DOWNLOAD_URL=
+ [[ -n '' ]]
+ sleep 1
+ for i in {1..3}
++ restify --user-agent=itzg/minecraft-bedrock-server --headers 'accept-language:*' --attribute=data-platform=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock
++ jq -r '.[0].href'
++ echo ''
+ DOWNLOAD_URL=
+ [[ -n '' ]]
+ sleep 1
+ for i in {1..3}
++ restify --user-agent=itzg/minecraft-bedrock-server --headers 'accept-language:*' --attribute=data-platform=serverBedrockLinux https://www.minecraft.net/en-us/download/server/bedrock
++ jq -r '.[0].href'
++ echo ''
+ DOWNLOAD_URL=
+ [[ -n '' ]]
+ sleep 1
+ [[ -z '' ]]
++ curl -s https://mc-bds-helper.vercel.app/api/latest
+ DOWNLOAD_URL=

**Comment by itzg** [comment]
There seems to be some kind of networking issue. Run this command to perform the same retrieval with curl in verbose mode:

```
docker run --rm --entrypoint curl itzg/minecraft-bedrock-server -A itzg/minecraft-bedrock-server -v https://www.minecraft.net/en-us/download/server/bedrock
```

**Comment by Wessi99** [comment]
docker run --rm --entrypoint curl itzg/minecraft-bedrock-server -A itzg/minecraft-bedrock-server -v https://www.minecraft.net/en-us/download/server/bedrock  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0* Could not resolve host: www.minecraft.net* Closing connection 0curl: (6) Could not resolve host: www.minecraft.net

**Comment by Wessi99** [comment]
I deactivated Pihole and restarted the Raspberry and now it works. Apparently it was the Pihole
