### ISSUE TITLE
Implement "MCscripts"?

### ISSUE THREAD

**Issue by xnaas** [itzg/docker-minecraft-bedrock-server#48]
Any chance of implementing some of the scripts from something like https://github.com/TapeWerm/MCscripts?

**Comment by itzg** [comment]
Most of those functions are implemented by equivalent features in this container's startup logic, etc.  Can you clarify what functions from those scripts are missing and desired?

**Comment by xnaas** [comment]
Mostly the webhook and IRC stuff.

**Comment by edward3h** [comment]
@xnaas I've implemented a docker service that does the Discord webhook function. Check it out here - https://github.com/edward3h/minecraft-webhook

**Comment by xnaas** [comment]
Eh, I no longer have this feature request.

**Comment by itzg** [comment]
@edward3h FWIW I added a link to your solution in https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/README.md#community-solutions. Thanks for creating that.
