### ISSUE TITLE
server.properties not being set

### ISSUE THREAD

**Issue by mattotone** [itzg/docker-minecraft-bedrock-server#5]
![image](https://user-images.githubusercontent.com/35114885/64051999-edeeb600-cb74-11e9-9123-0e8b01fe98f7.png)

Environment variables, 
unable to set to creative mode
unable to set default player to operator
unable to set chests on
Server name      does work
Online mode     does work

**Comment by mattotone** [comment]
cat server.propertise show that settings are being set

![image](https://user-images.githubusercontent.com/35114885/64052580-ee884c00-cb76-11e9-9ca1-1498f43a5008.png)

**Comment by bingobob** [comment]
hi - i don't quite get this...

do edit server.properties file to set things up as i want them?

Or do i set the environment variables in my docker-compose and then that in turn writes to the server.properties file when the container is restarted/ recreated.

i've got it working but confused on config ?

Tahnks for any help?

**Comment by mattotone** [comment]
I never managed to get the full config to work, I set the environment variables in docker and it wrote them to the config files.
Cat server.properties shows them being written but the server appears to ignore them. maybe a bug in the game?

**Comment by itzg** [comment]
Since the Bedrock server is still beta this does seem to be one of the glitches due to that. Basically, it acts like most of the properties are only consulted on very first world creation even though the server will echo the modified properties on every startup. Gamemode was the property that most annoyed me.

If you make sure to include `-i -t` in the `docker run`, then you can always [docker attach](https://docs.docker.com/engine/reference/commandline/attach/) to the running server and use [one of the commands](https://minecraft.gamepedia.com/Commands#List_and_summary_of_commands) to change the server behavior at any time.

**Comment by bingobob** [comment]
thanks for this, I'm running from a docker-compose file. Any tips to attach to the instance?

**Comment by itzg** [comment]
@bingobob with a compose file you'll set
```yaml
stdin_open: true
tty: true
```

on the service definition, [described here](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir). With that you can `docker attach`.

**Comment by creol** [comment]
How do I add opperators? I changed the permission.json but cant figure out how to apply the change.   I tried permissions reload and it does not accept that command in bedrock.

**Comment by itzg** [comment]
@creol did you try restarting the server/container to pick up the change? Otherwise I would suggest the `docker attach` approve above and use the [op command](https://minecraft.gamepedia.com/Commands/op) to change it at runtime.

**Comment by creol** [comment]
> @creol did you try restarting the server/container to pick up the change? Otherwise I would suggest the `docker attach` approve above and use the [op command](https://minecraft.gamepedia.com/Commands/op) to change it at runtime.

Apparently I am my own worst enemy! 
I created one MC container my kids were playing on while I have been working on a second container, but I accidentally forgot to remap the data folder. Both containers were working off the same /data/server.properties file, so of course nothing ever worked. Once I solved that I was able to make the default-player-permission-level=operator work. 
Thank you!

**Comment by bendinwire** [comment]
I have this exact same issue that @mattotone had above. Changes to the yml file alter the server.properties file and yet only one or two of them ever 'change'. Meaning I can change the MOTD, but the server name won't change. 

Examples yml file:
```version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "true"
      MOTD: "Chaos Vibes Only"
      SERVER_NAME: "den"
      SEED: "-7783854906403730143"
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
```

Produces server.properties file 
```
$ cat server.properties | grep name
level-name=world
server-name=den
```

Bringing up the server with docker-compose it shows the Minecraft's servers name as `Minecraft Server`

I'm really stumped as to why it's not taking the setting (yet the MOTD) was updated for some reason). I thought that `OVERRIDE_SERVER_PROPERTIES: "true"` would fix it but it didn't.

Any suggestions?

**Comment by itzg** [comment]
@bendinwire so the `server.properties` entry
```
server-name=den
```

reflects the environment variable setting of `SERVER_NAME: "den"`, right? If so, then this is an issue separate from the image startup scripts.

**Comment by bendinwire** [comment]
I agree with you that the yml seems to be producing the correct correlated file in server.properties, however when you view the server from a Minecraft client the name of the server still reads "Minecraft Server".

**Comment by itzg** [comment]
It sounds like an issue to report with Mojang.
