### ISSUE TITLE
Port Forwarding no longer working

### ISSUE THREAD

**Issue by otmpp** [itzg/docker-minecraft-bedrock-server#51]
I have tried both of your servers, java and bedrock. The java one works brilliantly I can connect to it remotely and everything like that. I decided to install your bedrock one as my friends all have that version. Initially the server was working and it could be connected to remotely but then I changed my router and now I just cannot get it to be accessed remotely. I have no idea what this could be as the java version still works and I have other things that are being forwarded that also can be accessed remotely without any issues. 
Do you have any idea what could be causing it?

Here are the logs for the server

> time="2020-05-09T16:13:38+01:00" level=debug msg="Using /data to match uid and gid"
time="2020-05-09T16:13:38+01:00" level=debug msg="Resolved 1000 from environment variable UID"
time="2020-05-09T16:13:38+01:00" level=debug msg="Resolved 100 from environment variable GID"
time="2020-05-09T16:13:38+01:00" level=debug msg="stdin is detached, so forwarding is disabled"
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2020-05-09 16:13:39 INFO] Starting Server
[2020-05-09 16:13:39 INFO] Version 1.14.60.5
[2020-05-09 16:13:39 INFO] Session ID 2a7aec4e-ac1e-486f-a432-a9c5740ea122
[2020-05-09 16:13:39 INFO] Level Name: Bedrock level
[2020-05-09 16:13:39 INFO] Game mode: 0 Survival
[2020-05-09 16:13:39 INFO] Difficulty: 2 NORMAL
[2020-05-09 16:13:39 INFO] opening worlds/Bedrock level/db
[2020-05-09 16:13:41 INFO] IPv4 supported, port: 19132
[2020-05-09 16:13:41 INFO] IPv6 not supported
[2020-05-09 16:13:41 INFO] IPv4 supported, port: 59749
[2020-05-09 16:13:41 INFO] IPv6 not supported
[2020-05-09 16:13:43 INFO] Server started.

**Comment by itzg** [comment]
It sounds like it's probably the router. Last weekend I had an issue where I couldn't connect to my java edition server via my public IP address and a router restart fixed it.

If your host is Linux or Mac based you can use `tcp dump -vv udp port 19132` to see if the client packets are even making it past the router.

**Comment by claflico** [comment]
I think it's one word: "tcpdump".

**Comment by itzg** [comment]
> I think it's one word: "tcpdump".

Thanks ;) iPhone auto-correct working against me

**Comment by marcusjwhelan** [comment]
What if tcpdump is not a recognized command in the container?

**Comment by otmpp** [comment]
I have restarted my router to no avail but it seems that when you try to connect to the server remotely it fails to make a connection and the udp fails. This is the tcp dump

> 13:59:59.094868 IP (tos 0x0, ttl 64, id 47849, offset 0, flags [DF],
proto UDP (17), length 61)
    192.168.0.239.42263 > 192.168.0.100.25565: [udp sum ok] UDP, length 33
13:59:59.095038 IP (tos 0x0, ttl 64, id 15572, offset 0, flags [DF],
proto UDP (17), length 151)
    192.168.0.100.25565 > 192.168.0.239.42263: [bad udp cksum 0x8338 ->
0x93f3!] UDP, length 123

same was true with port 19132

**Comment by itzg** [comment]
To clarify, I meant running tcpdump on the host and not within the container; however it can be apt installed there if that level of debugging is needed.

**Comment by itzg** [comment]
...as for the trace, I’ll have to compare with my system. That “bad checksum” report doesn’t seem good

**Comment by itzg** [comment]
Hmm, mine also reports a bad checksum in the response packets, but proceeds to connect fine from a Windows 10 client to a container running on Ubuntu host on my LAN:

```
00:57:02.919264 IP (tos 0x0, ttl 127, id 12860, offset 0, flags [DF], proto UDP (17), length 1492)
    Quattro.61980 > 172.17.0.2.19132: [udp sum ok] UDP, length 1464
00:57:02.919508 IP (tos 0x0, ttl 64, id 40881, offset 0, flags [DF], proto UDP (17), length 56)
    172.17.0.2.19132 > Quattro.61980: [bad udp cksum 0x9f1f -> 0x64d2!] UDP, length 28
00:57:02.930079 IP (tos 0x0, ttl 127, id 12862, offset 0, flags [none], proto UDP (17), length 62)
    Quattro.61980 > 172.17.0.2.19132: [udp sum ok] UDP, length 34
00:57:02.930518 IP (tos 0x0, ttl 64, id 40882, offset 0, flags [DF], proto UDP (17), length 63)
    172.17.0.2.19132 > Quattro.61980: [bad udp cksum 0x9f26 -> 0x637a!] UDP, length 35
00:57:02.940511 IP (tos 0x0, ttl 127, id 12864, offset 0, flags [none], proto UDP (17), length 56)
    Quattro.61980 > 172.17.0.2.19132: [udp sum ok] UDP, length 28
00:57:02.940946 IP (tos 0x0, ttl 64, id 40884, offset 0, flags [DF], proto UDP (17), length 35)
    172.17.0.2.19132 > Quattro.61980: [bad udp cksum 0x9f0a -> 0x630b!] UDP, length 7
```

**Comment by otmpp** [comment]
I have restarted my router to no avail but it seems that when you try to connect to the server remotely it fails to make a connection and the udp fails. This is the tcp dump

> 13:59:59.094868 IP (tos 0x0, ttl 64, id 47849, offset 0, flags [DF],
proto UDP (17), length 61)
    192.168.0.239.42263 > 192.168.0.100.25565: [udp sum ok] UDP, length 33
13:59:59.095038 IP (tos 0x0, ttl 64, id 15572, offset 0, flags [DF],
proto UDP (17), length 151)
    192.168.0.100.25565 > 192.168.0.239.42263: [bad udp cksum 0x8338 ->
0x93f3!] UDP, length 123

same was true with port 19132

**Comment by otmpp** [comment]
Hmmm that's interesting then. I did run the tcpdump from the host itself and not the container. I wonder what it is then because as I said the java version of your server runs flawlessly on this new router

**Comment by itzg** [comment]
Bedrock server is a whole different animal since it uses UDP instead of TCP, so there could be any more of networking issues working against you. I’m not sure if I can help much more since the image itself works fine and I have confirmed port forwarding on a few systems.

**Comment by otmpp** [comment]
That's fine it's something which I thought anyways when I put this post but thought I may as well try anyways just in case. Thank you for trying, I appreciate it
