### ISSUE TITLE
error while loading shared libraries: ./libCrypto.so: file too short

### ISSUE THREAD

**Issue by marcusjwhelan** [itzg/docker-minecraft-bedrock-server#54]
I get this when the container is starting up in the logs. 
I am not completely sure what that means but the server is not accessible.

**Comment by itzg** [comment]
It sounds like something went wrong when downloading or unzipping the server archive. If you delete the "bedrock_server-*" file from the data directory and restart the container then it will force it to re-download an extract the server and crypto library.

**Comment by marcusjwhelan** [comment]
I found that the server needed at least 3 gb of disk space for the full bedrock server to download.
