### ISSUE TITLE
Use of MakeCode?

### ISSUE THREAD

**Issue by namurdock** [itzg/docker-minecraft-bedrock-server#63]
HI, got everything all working nicely the kids hare happy and their friends are accessing the server. Nice and stable. Good work!!!

I'd like to start getting them to play with some coding and was thinking of running MakeCode with the minecraft connect app. However I cannot seem to connect from the world to the app. /command (from chat) returns a command not found.

I have Cheats enabled and can see the toggle is change in the pause menu. (however i did change this after the world was crated via the server.properties file as i didn't want them to loose their world.

Can you confirm if this should be possible or not or am i missing something?

Thanks!

**Comment by itzg** [comment]
That's so great to hear.

I wonder if the command will need to be run from the server, in which case, you will need to `docker attach [container ID or name]`, issue the commands, and the Ctrl-p, Ctrl-q to detach.

**Comment by namurdock** [comment]
Oh cool. I'll give that a try and let you know.

**Comment by namurdock** [comment]
nope, doesn't look like it. connect isn't a command in there either.

**Comment by itzg** [comment]
Hmm, was the MakeCode support added via a plugin? Plugins are a little iffy on the server side since it quietly ignores ones that it deems not applicable.

**Comment by namurdock** [comment]
Sorry slow to respond. from the makecode documentation

[setup/minecraft-windows10](https://minecraft.makecode.com/setup/minecraft-windows10)

you should be able to just turn on cheats and then use the /connect command. But the command doesn't appear to be present.

I was wondering if i needed to drop a plugin somewhere? (total noob in the Minecraft game)

**Comment by itzg** [comment]
Plugins/addons, etc don't seem to be very compatible with the server-side. I'm guessing that's one of the aspects that is compromised since the server is in alpha.

**Comment by namurdock** [comment]
Yeah, i came to the same conclusion. Thanks for your input though, and a great container! Still keeping the kids and their friends occupied.
