### ISSUE TITLE
New .x Version

### ISSUE THREAD

**Issue by xnaas** [itzg/docker-minecraft-bedrock-server#67]
1.16.0.2 is the latest version now. Didn't want to just replace it on the https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/bedrock-entry.sh file but don't know how to safely add a new version either without breaking other things.

**Comment by ult1m8** [comment]
Yep, my girls are going to kill me this evening when they can't log into our local minecraft server.

**Comment by plankman2k** [comment]
Restart the container and it should update to the latest version. I had the same issue earlier, and when I tried to restart the container again it downloaded the latest server version

**Comment by ult1m8** [comment]
Ah yes, I'm an idiot.  I assumed since bedrock-entry.sh didn't contain 1.16, it would not download.  Looking closer, the * section will download the latest.

**Comment by hansenms** [comment]
I added a PR #69 to add this. But yes it should get the latest if you restart.

**Comment by xnaas** [comment]
Thanks for taking care of that. Wasn't sure what all needed to be changed. Turns out, not very much! 😄

**Comment by hansenms** [comment]
@xnaas there may be some other fixes needed, but this was "good enough" for me. @itzg may have some additional comments.

**Comment by itzg** [comment]
PR #69 has been merged, but FYI I'm thinking I should also change the "default case" to actually match "LATEST". That would be clearer when looking at the code and have this image act more consistently with [my java edition image's handling of "LATEST"](https://github.com/itzg/docker-minecraft-server/blob/f2c9d2f905a65e988f706fb05ef853583417f0e5/start-configuration#L52).
