### ISSUE TITLE
How To: Nether Reset

### ISSUE THREAD

**Issue by C-VTI** [itzg/docker-minecraft-bedrock-server#74]
great project - we are big fans!

after upgrading to 1.16 it would be great to reset the nether so even known (close) nether locations can benefit from the new biomes.

I found tutorials for bedrock and java editions with the MCC Toolchest PE world editor (http://mcctoolchest.com/)

But the tool doesn't recognise the files in data volumn of the docker container.

Any advice would be highly appreciated!

**Comment by itzg** [comment]
Double check that you're pointing it at the subdirectory of the container's `/data/worlds` directory named from the `LEVEL_NAME`. By default that'll be `/data/worlds/Bedrock level`.

**Comment by C-VTI** [comment]
Thanks a lot! my mistake, the copy of the data folder was corrupt. After coping it again, it worked perfectly like you described.
