### ISSUE TITLE
Problem with new installs

### ISSUE THREAD

**Issue by neutronstorm** [itzg/docker-minecraft-bedrock-server#75]
Hello, the commit yesterday [3b49c32](https://github.com/itzg/docker-minecraft-bedrock-server/commit/3b49c32386f55d969d0449587a60488f5c42b880) has an issue for people without an existing /data directory, ie. a new installation. The change excludes the creation of 3 critical files for a new install. You should only exclude those files if they already exist. I made this simple change to fix it on my machine. However, you will probably want to do something more sophisticated. 
 ```
   # ... overwrite all game files, except config files
-  unzip -q ${TMP_ZIP} -x server.properties whitelist.json permissions.json
+  unzip -q ${TMP_ZIP} -x `ls server.properties whitelist.json permissions.json`
   rm ${TMP_ZIP}
```

**Comment by itzg** [comment]
Thank you so much @neutronstorm for reporting this and suggesting a great fix. Obviously, I need to do be doing some validation during CI/CD of PRs/commits. It's "good" timing actually since I was about to convert this repo over to github actions soon.

**Comment by itzg** [comment]
This fix is now pushed to Docker Hub.
