### ISSUE TITLE
Existing Installation All Biomes Stone - BDS 6230 BUG

### ISSUE THREAD

**Issue by cperalt1** [itzg/docker-minecraft-bedrock-server#76]
Per Bug Report, Update to 1.16 from earlier version is only half complete because only the executable is updated and the other support files are not.
https://bugs.mojang.com/projects/BDS/issues/BDS-6230?filter=allopenissues

**Comment by itzg** [comment]
Can you confirm you are running the latest image? This issue was already fixed as of https://github.com/itzg/docker-minecraft-bedrock-server/commit/e045ca647c1a1e9808ea6acfa81c68ad7a81607d

**Comment by cperalt1** [comment]
Thanks, I had failed to update my local docker image, I can confirm this works appropriately on the newest image.
