### ISSUE TITLE
New world generation creates cobblestone only worlds.

### ISSUE THREAD

**Issue by Dannington** [itzg/docker-minecraft-bedrock-server#78]
When I create a new world by adjusting the server.properties file the world is formed / terrained but it's entirely made of cobblestone or water.  There are some prefab type objects like villages and monuments.

I've tried making a world in desktop minecraft and copying it to the docker folder.  This works, but when you travel outside the 'known area', any new segments of game are created in the same way - just cobblestone.

FYI I'm running on a QNAP nas - no problems with builds prior to 1.16.x

**Comment by itzg** [comment]
It sounds like you might be using a version of the image before upgrade handling was fixed. Try this to see if it fixes things:

1. Stop the container
2. Remove the server binary `bedrock_server-*` from the attached data directory
3. `docker pull itzg/minecraft-bedrock-server`
4. Start the container again

**Comment by R0tt3eR** [comment]
My sons server got the same issue after the upgrade to the latest, and the suggested solution do now work. 
Blocks affected are still cobblestone even when I copy and look at the world locally to the win10 computer. 
So seems to be permanent.

![Minecraft 03_07_2020 00_04_33](https://user-images.githubusercontent.com/67764920/86416418-c5b67300-bcc1-11ea-97e9-e3ae97ce06d9.png)
![Minecraft 03_07_2020 00_04_49](https://user-images.githubusercontent.com/67764920/86416423-c6e7a000-bcc1-11ea-8772-e4c0b88fd658.png)
![Minecraft 03_07_2020 00_05_15](https://user-images.githubusercontent.com/67764920/86416425-c818cd00-bcc1-11ea-89c7-66dee0f85f0d.png)
![Minecraft 03_07_2020 00_05_50](https://user-images.githubusercontent.com/67764920/86416426-ca7b2700-bcc1-11ea-993d-2ade1b3ae63a.png)
![Minecraft 03_07_2020 00_06_36](https://user-images.githubusercontent.com/67764920/86416431-cbac5400-bcc1-11ea-8c14-1a687e29b1b7.png)
![Minecraft 03_07_2020 00_07_19](https://user-images.githubusercontent.com/67764920/86416433-ce0eae00-bcc1-11ea-8a74-f06b2d98073c.png)
![Minecraft 03_07_2020 00_07_34](https://user-images.githubusercontent.com/67764920/86416438-cf3fdb00-bcc1-11ea-9949-8742f1ae5fd8.png)
![Minecraft 03_07_2020 00_07_55](https://user-images.githubusercontent.com/67764920/86416442-d1a23500-bcc1-11ea-8dfa-8df6630ca36e.png)
Examples attached:

**Comment by itzg** [comment]
Yes, I am afraid whatever causes that in the first place makes permanent changes to the world chunks. 

To confirm though, you found after the upgrade sequence that the world data no longer gets new chunk corruption, right?

**Comment by R0tt3eR** [comment]
itzg,Sorry for the late reply. 
Yip, asked my son and that seems to be the case, no new areas seems to be corrupted after the upgrade.
