### ISSUE TITLE
Lock to specific version

### ISSUE THREAD

**Issue by igoticecream** [itzg/docker-minecraft-bedrock-server#79]
Hello, I'd like to request a feature to lock onto a specific server version.

Setting VERSION=1.16.1.02 should download that extact version, but currently its ignored and it download the latest.

This is useful to avoid bugs or broken mechanics that an early version could introduce.

Thanks

**Comment by itzg** [comment]
I had already been planned on improving the conditional for LATEST, so I’ll adjust the specific version handling while I’m in there.

**Comment by igoticecream** [comment]
Thanks you.

Im not a bash expert but would this change be as easy as changing `*)` to `LATEST)` in the entry point script?

**Comment by itzg** [comment]
Pretty much, yep :) and then I'll re-purpose the wildcard `*` for the specific version retrieval case you requested.

**Comment by igoticecream** [comment]
Thansk you. I appreciate it

**Comment by itzg** [comment]
Thank you for making the request. This is now available on Docker Hub.
