### ISSUE TITLE
¿How attach to server console?

### ISSUE THREAD

**Issue by Nitrosito** [itzg/docker-minecraft-bedrock-server#8]
Hi

Is it possible to enter commands to the minecraft server by attaching to the container? How do we do it? If I attach to the container I don't see that I can enter commands.

I speak of commands for the minecraft server executable, not of commands to the container.
a greeting

**Comment by itzg** [comment]
`docker attach` should work in some form; however, I haven't experimented to see what combination of parameters need to be set on the container initially. I'm guessing `-i` and `-t` are probably needed on the `docker run` (or the equivalent settings in compose).

With that said, the bedrock server doesn't natively support rcon, which is what gets leveraged in [my Java edition image](https://github.com/itzg/docker-minecraft-server). I'm thinking of enhancing the process wrapper with rcon or rcon-like console support, so that commands can be sent more easily.

**Comment by itzg** [comment]
...as a quick experiment, I started a container with

```
docker run --rm -it -e EULA=TRUE itzg/minecraft-bedrock-server
```

and was able to attach and send the "help" command using:

```
docker attach 3c1633c5e90b
DEBU[0076] Forwarding signal                             signal="window changed"
DEBU[0076] Forwarding signal                             signal="window changed"
help
§2--- Showing help page 1 of 18 (/help <page>) ---
/? [command: CommandName]
/? <page: int>
/alwaysday [true|false]
/changesetting allow-cheats <true|false>
/changesetting difficulty <value: Difficulty>
/changesetting difficulty <value: int>
/clear [player: target] [itemName: Item] [data: int] [maxCount: int]
§2Tip: Use the <tab> key while typing a command to auto-complete the command or its arguments
read escape sequence
```

I then used `Ctrl-P` and `Ctrl-Q` to detach and leave the container running.

Is that sufficient for your deployment?

**Comment by Nitrosito** [comment]
Of course @itzg !
I modify my docker-compose to set similar entrypoint

Thanks and regards

**Comment by bingobob** [comment]
I was trying to do the same thing. i.e. attach to server console to monitor stuff and issue commands. Would be interested in any progress here. thanks. good work, thanks for this.

**Comment by cyclingwithelephants** [comment]
Hi folks, to get into the shell of a running container you should execute
```
kubectl exec -it --namespace ${NAMESPACE} ${POD_ID} bash
```

this opens a bash terminal that you can use to navigate, in the present working directory of the container. YOU NEED the -it flags, the i stands for interactive (I forget what t stands for, but `man kubectl` is your friend)

**Comment by Oliver84** [comment]
> Of course @itzg !
> I modify my docker-compose to set similar entrypoint
> 
> Thanks and regards

Can you share how you attached to this with docker-compose? I started the server with docker-compose but when I attached, it's not taking any of my input commands.

**Comment by itzg** [comment]
@Oliver84 in your compose file you'll need these two items:

https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/examples/docker-compose.yml#L14-L15

With that and restarting the container you'll then be able to use `docker attach`.

**Comment by dominic-ks** [comment]
Hey @itzg, sorry to comment on an old issue, but can I clarify that it's suggested here that I should be able to just use `docker attach` and then run commands for the Minecraft server directly in the terminal? I can attach no problem, and have tried with the `stdin_open` and `tty` options you pointed to in the example compose file, but I just get a regular bash terminal, running `help` just shows me linux commands, and attempting to run any Mincraft commands it tells me they're not found. Have I missed something?

**Comment by dominic-ks** [comment]
> you're not doing something right

Yep, I assumed that using the VS Code Docker extension and clicking "attach" on it would run attach, which I guess it does not.

Cheers!

**Comment by DaanSelen** [comment]
> To get into the shell of a running container you should execute
> 
> ```
> kubectl exec -it --namespace ${NAMESPACE} ${POD_ID} bash
> ```
> 
> this opens a bash terminal that you can use to navigate, in the present working directory of the container. YOU NEED the -it flags, the i stands for interactive (I forget what t stands for, but `man kubectl` is your friend) from this point you can use the excellent rcon-cli tool by the same author.
> 
> Iif you're using docker but not k8s then replace `kubectl` with `docker` and remove the namespace argument, the pod ID will instead be the UID of the container, I believe you can find this using `docker ps` (I may be forgetting some flags)

In the java edition this rcon-cli is packed with the container where can I get this?
