### ISSUE TITLE
Download server down. 

### ISSUE THREAD

**Issue by apsco** [itzg/docker-minecraft-bedrock-server#87]
The download page at https://www.minecraft.net/en-us/download/server/bedrock/ is broken and missing download links.
(not your issue).

I got around it by specifying the VERSION=1.16 which I had already downloaded. But it would be good to have an option for skip download and just use last downloaded version...

**Comment by itzg** [comment]
The latest image will now use the existing `bedrock_server-*`, if present, when the version lookup fails. It seemed reasonable to have it always fallback like that rather than making it an option.

**Comment by apsco** [comment]
Thanks
