### ISSUE TITLE
Minecraft Bedrock Server Website MIA

### ISSUE THREAD

**Issue by NathanGilbert2** [itzg/docker-minecraft-bedrock-server#88]
Minecraft Bedrock site for the server download is currently MIA. Creating this issue since others may run into this error if they are trying to set up a server today.

`Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/`

Current bug report: [BDS-7631](https://bugs.mojang.com/browse/BDS-7631)

**Comment by itzg** [comment]
Thanks for the bug report link. I'll figure out a workaround like suggested in #87

**Comment by itzg** [comment]
The latest image will now use the existing `bedrock_server-*`, if present, when the version lookup fails.

**Comment by arschmitz** [comment]
@itzg thank you for the super fast response and fix on this issue but im still having the issue even after updating to the latest code. I had the server running on two different machines (both were actually fresh installs just before this issue started happening a day or so ago) and neither one will start even after your update. Is there anything else i bneed to do? 

```
Starting docker-minecraft-bedrock-server_bds_1 ... done
Attaching to docker-minecraft-bedrock-server_bds_1
bds_1  | DEBU[0000] Using /data to match uid and gid
bds_1  | DEBU[0000] Resolved UID=0 from match path
bds_1  | DEBU[0000] Resolved GID=0 from match path
bds_1  | Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
bds_1  | 2020/07/23 12:51:56 Unable to find an element with attribute matcher data-platform=serverBedrockLinux
```

**Comment by itzg** [comment]
That's strange. Can you triple check you have the latest image by doing a `docker-compose pull` or `docker pull itzg/minecraft-bedrock-server`?

Adding `VERSION: 1.16.1.02` will probably fix the issue too but would be nice for the new change to kick in.

**Comment by itzg** [comment]
...and can also compare the pulled image ID using:

```
docker image inspect itzg/minecraft-bedrock-server -f '{{.Id}}'
sha256:3773da820343869d38ce7db44e845d17a3976a2102b7a304e318696b688bec85
```

**Comment by jag100UK** [comment]
I have the same issue when running docker on unbuntu

```
~$docker pull itzg/minecraft-bedrock-server

Using default tag: latest
latest: Pulling from itzg/minecraft-bedrock-server
Digest: sha256:babe67632af1369b971afb192d3bc2350ecfb3260a30cc5d59181835bd292ac4
Status: Image is up to date for itzg/minecraft-bedrock-server:latest
docker.io/itzg/minecraft-bedrock-server:latest

~$ docker start -i -a mc-family
DEBU[0000] Using /data to match uid and gid
DEBU[0000] Resolved UID=0 from match path
DEBU[0000] Resolved GID=0 from match path
DEBU[0000] Forwarding signal                             signal="window changed"
Failed to extract download URL '' from https://www.minecraft.net/en-us/download/server/bedrock/
2020/07/23 20:08:58 Unable to find an element with attribute matcher data-platform=serverBedrockLinux
DEBU[0000] Forwarding signal                             signal="child exited"
john@john-NUC10i7FNH:~$ docker run -d -it -e EULA=TRUE -p 19132:19132/udp itzg/minecraft-bedrock-server
02bf22dc5252a4c4c1ac12ded6997177a99f615f75fc1cb6f47b1dac42dfc825

```

**Comment by jag100UK** [comment]
Its working again, now.
"Thank you" to whoever fixed it.

**Comment by jag100UK** [comment]
Its working again, now

"Thank you" to whoever fixed it

**Comment by itzg** [comment]
Making a note for myself that the page seems to have moved to language scoped path

https://www.minecraft.net/en-us/download/server/bedrock/
