### ISSUE TITLE
Port forwarding in docker? Can’t see server

### ISSUE THREAD

**Issue by mschindl** [itzg/docker-minecraft-bedrock-server#9]
Hello

Do you why I can’t get my second visible to a client (i.e iOS)?

iPhone and iPad has different view, but both don‘t the server MSCREA :/

———
SURVIVAL

locpath=/Users/marc/docker/minecraft-surv

docker run -d -it -e EULA=TRUE -p 19132:19132/udp -e SERVER_NAME=MSSURVIVAL -e ONLINE_MODE=false -e MAX_PLAYERS=50 -v $locpath:/data -e LEVEL_TYPE=DEFAULT -e GAMEMODE=survival -e DIFFICULT=peaceful --restart unless-stopped --name minecraft-surv itzg/minecraft-bedrock-server

CREATIVE

locpath=/Users/marc/docker/minecraft-crea

docker run -d -it -e EULA=TRUE -p 19135:19132/udp -e SERVER_NAME=MSCREA -e ONLINE_MODE=false -e MAX_PLAYERS=50 -v $locpath:/data -e LEVEL_TYPE=DEFAULT -e GAMEMODE=creative -e DIFFICULT=peaceful --restart unless-stopped --name minecraft-crea itzg/minecraft-bedrock-server

———

![FF9414A4-5407-488B-850A-7FC0827EF86C](https://user-images.githubusercontent.com/26382876/64490089-eb1d5080-d259-11e9-8416-ba19838e71da.jpeg)
![041515D9-9792-42E9-B3A2-816866B9502F](https://user-images.githubusercontent.com/26382876/64490090-eb1d5080-d259-11e9-91d1-6d72baf9e62f.jpeg)
![B0959BB5-3480-4FD2-ADFB-F554371A9E7D](https://user-images.githubusercontent.com/26382876/64490226-15234280-d25b-11e9-9728-c090a5ff76bf.jpeg)

**Comment by itzg** [comment]
I actually hadn't tried running on a port other than 19132. I just now tried it and at first the client (Windows 10) didn't connect. After quickly trying my 19132 server I tried connecting again to the 19135 and it succeeded. What's strange is the "Servers" view still shows a red indicator.

Can you try again to see if you are able to connect to your 19135 instance even though the status is showing red?

**Comment by mschindl** [comment]
You are right. I have to try it more as once and sometimes it works with the first try.
Thank you

**Comment by mschindl** [comment]
Sorry, but it's still not working if I have two containers running, because the iOS app still connect to Container 1 instead of Container 2. If I stop Container 1 then I can connect to Container 2 on the right port :/

Container 1: Survival Mode on Port 19132
Container 2: Creative Mode on Port 19135

`docker run -d -it -e EULA=TRUE -p **19132:19132**/udp -e SERVER_NAME=MSSURVIVAL -e LEVEL_NAME=MSSURVIVALLEVEL1 -e ONLINE_MODE=false -e MAX_PLAYERS=20 -v $locpath:/data -e LEVEL_TYPE=DEFAULT -e GAMEMODE=SURVIVAL -e DIFFICULT=survival --restart unless-stopped --name minecraft-surv itzg/minecraft-bedrock-server`

`docker run -d -it -e EULA=TRUE -p **19135:19132**/udp -e SERVER_NAME=MSCREATIVE -e LEVEL_NAME=MSCREATIVELEVEL1 -e ONLINE_MODE=false -e MAX_PLAYERS=50 -v $locpath:/data -e LEVEL_TYPE=DEFAULT -e GAMEMODE=creative -e DIFFICULT=PEACEFUL --restart unless-stopped --name minecraft-crea itzg/minecraft-bedrock-server`

Any idea why?

**Comment by itzg** [comment]
Your `docker run` usage looks correct. I'll test it out again using the iOS client.

**Comment by itzg** [comment]
I'm sorry @mschindl , this issue fell off my radar and I am just now getting back to researching this. I was able to create two separate servers like yours and connect in the iOS version with two separate configurations; however, when I went to reconnect both failed until I forced the iOS client to exit. After starting the client again the connections worked again.

Are you finding that connecting to your creative server fails or does it connect to the survival server (on port 19132) instead?

**Comment by mschindl** [comment]
> After starting the client again the connections worked again.
You are right, if mean the visibility in the iOS client. But, you can also add a server manually and mostly it worked without restart the app.

> Are you finding that connecting to your creative server fails or does it connect to the survival server (on port 19132) instead?
That's the issue, the iOS client connect everytime to port 191**32** instead to use the port 191**35**

Following configuration in the iOS app doesn't work and it tries to connect always on the port 191**32**. I saw it on the container logs that the user always connect to container**1** and not to the second one with the creative mode.

![image](https://user-images.githubusercontent.com/26382876/67719447-1dce0480-f9d2-11e9-9b21-fef2d5aae9f8.png)

**Comment by mschindl** [comment]
I tested it again and it worked currently :/
I will come back when I know what was the issue... (I upgraded a lot of times Ubuntu after I opened the issue #9)

Thank you for your help

**Comment by itzg** [comment]
I’m suspecting the UDP routing is making less stable than I know I’m used to with the Java edition server. Speaking of Ubuntu, when I tried this with microk8s the network connectivity didn’t work at all.

**Comment by mschindl** [comment]
Solution for me is:

# docker network create -d macvlan --subnet=10.1.1.0/24 --gateway=10.1.1.254 -o parent=enp0s31f6 net-mc

docker run -d -it \
-e EULA=TRUE -p 19132:19132/udp \
-e SERVER_NAME=MC-Kreativ1 \
-e LEVEL_NAME=MC-Kreativ1 \
-e ONLINE_MODE=false \
-e MAX_PLAYERS=50 \
-v $locpath:/data \
-e LEVEL_TYPE=DEFAULT \
-e GAMEMODE=creative \
-e DIFFICULTY=normal \
**--net net-mc \
--ip=10.1.1.2 \**
--restart unless-stopped \
--name mc-crea1 itzg/minecraft-bedrock-server
