### ISSUE TITLE
Container health status was unhealthy

### ISSUE THREAD

**Issue by zhuwenbing** [itzg/docker-minecraft-bedrock-server#91]
I've got the following message, and I can't connect my server. I can't figure out what's the problem. Please help me. Thank you first.
Last output | 2020/07/28 16:29:38 failed to query bedrock server localhost:19132: timeout reading the response: read udp [::1]:55049->[::1]:19132: read: connection refused
-- | --

The docker-compose.yml was like this.
```bash
  mcpe:
    image: itzg/minecraft-bedrock-server
    container_name: mcpe-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mcpe:/data
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      ONLINE_MODE: "false"
    stdin_open: true
    tty: true
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    restart: always
```

**Comment by itzg** [comment]
Using host network mode is breaking the health check. Do you really want to use that mode? Why not just use port mappings?

**Comment by zhuwenbing** [comment]
Not really want. I've changed to use port mappings and it works. Thank you very much!
