### ISSUE TITLE
Not working with latest iOS MC client

### ISSUE THREAD

**Issue by markmarino** [itzg/docker-minecraft-bedrock-server#92]
Looks like the bedrock server container is not allowing the recently updated MC iOS client to connect. Is the server container going to be updated to support the latest client?

**Comment by itzg** [comment]
I started a fresh container and was able to connect fine from my iPhone. Can you provide container startup logs and the docker run or compose file you're using to create the container?

FYI my iOS client is reporting v1.16.20 and the container auto downloaded server version 1.16.20.3

**Comment by markmarino** [comment]
I’m running 1.6.20 client like you. Sorry for the noob question, but how can I check the server version? I’m running via SYNOLOGY NAS Docker app. I can connect to console via PuTTY.

**Comment by itzg** [comment]
Yes, you have to manually restart to pick up updates. It would be disruptive to have people's Minecraft servers sporadically restart whenever a new version showed up.
