### ISSUE TITLE
Suggestion Pocketmine support

### ISSUE THREAD

**Issue by Fireant456** [itzg/docker-minecraft-bedrock-server#95]
Been using your Java container for a while now. Love your work!

Have you considered adding other bedrock server types such as PocketMine?

**Comment by Fireant456** [comment]
My dumbass didn't realize PocketMine had an official docker container :)

**Comment by itzg** [comment]
It actually looks pretty easy to add support, but yeah if they have an official image then that would be better.

**Comment by Fireant456** [comment]
What I am finding out is that all the community-made servers for Bedrock seem to be behind in getting up to date with Vanilla. It is a shame, I think I might end up using the official server until the community servers catch up a little more or we get tired of the world save we are on. :P
PocketMine has a different world format and sadly can't run the LevelDB format that the PC version uses atm.
