### ISSUE TITLE
Set ipv6 port

### ISSUE THREAD

**Issue by sheepa** [itzg/docker-minecraft-bedrock-server#96]
Could you possible add an environment variable for setting the ipv6 port? Running net host will still get a port conflict on the ipv6 port since it cannot be changed.

**Comment by itzg** [comment]
I'll have to investigate if that's even configurable. Some of the port allocation is strange in the Bedrock edition server. 

Regardless, I'm curious why regular bridge networking and port mapping won't work? I have yet to encounter a case where host networking was required.

**Comment by sheepa** [comment]
It can cause errors in plugins that consult the port of the servers through a database, since all the servers will report that they are running on port 19132. Bridged networking also have a slightly worse performance.

**Comment by itzg** [comment]
Looks like a property mapping will need to be added for `server-portv6`

**Comment by itzg** [comment]
The latest image now support the environment variable `SERVER_PORT_V6` to set that.
