### ISSUE TITLE
Had to mount a /tmp folder when mounting /data

### ISSUE THREAD

**Issue by rharkes** [itzg/docker-minecraft-bedrock-server#98]
Docker container started normally when not mounting any volumes. When mounting /data I got the following error:
`/opt/bedrock-entry.sh: line 38: /tmp/restify.out: Permission denied`

So I mounted /tmp and the docker container started again.

My server is a synology NAS 918+ with DSM 6.2.3-25426 Update 2 running docker 18.09.0-0513

**Comment by itzg** [comment]
The runs as the user that owns `/data`, so I'm guessing it created that temp file as root, left it behind, and then when running as non-root with new `/data` mount it couldn't overwrite.

I'll fix the code to remove that temp file so that a change in user is handled correctly.

**Comment by itzg** [comment]
The latest image on Docker Hub now includes this fix.

**Comment by rharkes** [comment]
I just verified, the fix works. Thanks!!
